### ISSUE TITLE
Add a warning for Loan or Application Numbers regarding privacy

### ISSUE THREAD

**Issue by ericspry** [cfpb/hmda-platform-ui#1009]
The HMDA regulations strongly encourage filers to avoid using customer personal information in the loadID field.  In order to remind filers and highlight potential concerns, we need to make two changes to the platform:

1. Post a notice to filers, on the platform or institution landing page (or similar). This can be done ahead of the next item. 

2. The backend will be able to detect loadIDs that are all alpha characters or ###-##-#### pattern when [#1464](https://github.com/cfpb/hmda-platform/issues/1464) ticket is complete. This will work in the same way as a quality edit. To support this work, we need to design how the alert will appear, the language in the edit, and the user interaction (same as quality edits, unique, etc.). 

For both, the guidance comes from [1003.4(a)(1) comment 4](https://www.consumerfinance.gov/eregulations/1003-4/2015-26607_20170101#1003-4-a-2) which states in regards to Application or Loan Number:  
>Institutions are strongly encouraged not to use the applicant's or borrower's name or social security number, for privacy reasons.

**Comment by awolfe76** [comment]
Thanks, @ericspry.

> Post a notice to filers, on the platform or institution landing page (or similar). This can be done ahead of the next item.

No problem. We can add it anywhere we need to, but a warning like that seems to make the most sense on the `/upload` page when we have a filing status of `1` (no data has been uploaded yet). We'll just need to work out the content this.

> The backend will be able to detect loadIDs that are all alpha characters or ###-##-#### pattern when #1464 ticket is complete. This will work in the same way as a quality edit. To support this work, we need to design how the alert will appear, the language in the edit, and the user interaction (same as quality edits, unique, etc.).

No problem either. My quick take is that we should add this to the existing quality edits but in the UI we can look for that edit ID (we'll just need to know what it's called in https://github.com/cfpb/hmda-platform/issues/1464) and then highlight it by doing something like

- making it the first edit shown on that page and
- giving it some extra styling so it shows up more.

_The content for the edit will come from the back-end. So we'll have to add get it ready and add to https://github.com/cfpb/hmda-platform/issues/1464._

**Comment by keileyo** [comment]
Below is the cleared language of the notice to be added to the upload page. The cleared content that should be returned when the edit is flagged is posted in  cfpb/hmda-platform#1464.

_"Institutions are strongly encouraged not to use the applicant’s or borrower’s name or Social Security number in the Loan/Application Number field, for privacy reasons."_

**Comment by awolfe76** [comment]
[The PR](https://github.com/cfpb/hmda-platform/pull/1487) for https://github.com/cfpb/hmda-platform/issues/1464 has been merged.

We're good to go to add updates to this edit to the UI.

**Comment by keileyo** [comment]
alert: this edit should not actually be referred to as Q666 in the UI. i think @designlanguage is working on how it should be returned in the UI.

**Comment by awolfe76** [comment]
We are rendering what we get from the back-end. They should update that information there.

**Comment by awolfe76** [comment]
I created https://github.com/cfpb/hmda-platform/issues/1491 to update the language and edit name.
