### ISSUE TITLE
Quality Edits Page bug

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform-ui#1010]
1. On the Quality Edits page, I checked the "verify edits" checkbox
1. I pressed the "Review Macro Edits" button
1. On the resulting page, the URL bar, nav bar, and yellow info box all correctly refer to Macro edits, but the content of the page is all Quality edits.

<img width="1126" alt="screen shot 2018-02-01 at 3 11 47 pm" src="https://user-images.githubusercontent.com/4295388/35701135-13126ec2-0763-11e8-8c96-4e03833bef27.png">

And at the bottom of the page, there is no button to continue to the next page

<img width="547" alt="screen shot 2018-02-01 at 3 18 57 pm" src="https://user-images.githubusercontent.com/4295388/35701217-4b984db6-0763-11e8-9258-318d934ba855.png">

**Comment by wpears** [comment]
~I've been unable to repro this, pulling all my tricks out of the bag. I'll look at the code to see under what circumstances this could happen (seems like the Edits container wasn't re-rendered when it should have been). May be a weird timing issue that occurs 1 time out of 100 but that we can still guard against without a repro.~

**Comment by wpears** [comment]
I've discovered a repro, just requires paging on a quality edit then verifying and moving on to macro edits. Will work on a fix this evening. Might require a hotfix release of the front-end tomorrow or the next day. @awolfe76

**Comment by wpears** [comment]
Closed by #1038
