### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1017]
_This one is sort of "out there", but I use them in a few places and it made me wonder if they would be useful in our app._

Would hotkeys be useful to filers?

For example - 
- `u` to upload a file from the institutions page
- `r` to resubmit (would trigger the confirmation modal)
- `<` or `>` to navigation the submission screens
- `v` to verify
- `s` to sign (check the checkbox)
- `h` to view/hide the filing history (expand/collapse the history)
- `d` to download the current edit report
- `i` to download the IRS report

Again, we should know if these would be useful/used first ... and please feel free to tell me this is crazy. 😄

**Comment by wpears** [comment]
THIS IS CRAZY

**Comment by wpears** [comment]
...but actually I can see where you're coming from but I think that just making sure everything is fully keyboard accessible I think is a big enough win here (it already should be, but there might be parts that could be smoother on the keyboard).

I think we'd probably generate enough confusion that the time savings from hotkeys would be minimal, especially cause we'd have to create a way to list them out and such.

Implementation wouldn't be bad as you'd just dispatch appropriate actions mapped to the keys.. but I'm still in the not-unless-we-see-the-business-need camp for now
