### ISSUE TITLE
Update progress bar

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1020]
_Some of these ideas will need a bit of playing/prototyping but are things we can improve so just want to get the ideas down here._

- [ ] make it more realistic (if we can get better data from the back-end)
- [ ] improve the text that appears below the bar (positioning, spacing, etc)
  - can we make the content more clear?
- [x] highlight the drop area when hovered with a file (#1021)

**Comment by wpears** [comment]
Also:
 - [ ] [progress bug](https://github.com/cfpb/hmda-platform-ui/issues/972)
 - [ ] [Multi-filers bug](https://github.com/cfpb/hmda-platform-ui/issues/1012)

**Comment by colleenms** [comment]
Suggestion from filer interviews to split the upload and validation steps into separate bars and show progress for each

**Comment by awolfe76** [comment]
While a lot of this still applies, closing in favor of #1106.
