### ISSUE TITLE
Content review and improvements

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1023]
After this first filing season, it would be good to review the content throughout the application and find areas for improvement, to clean up messaging (less is more).

- [ ] edit and edit type descriptions
- [ ] error/warning messages
- [ ] progress descriptions
- [ ] IRS, summary, and signature blocks
- [ ] others?

**Comment by colleenms** [comment]
One of the suggestions from filer interviews was to make the “download edit report” and "upload a new file" links more prominent. We should also consider adding an option to download the final edit report on the submission page.
