### ISSUE TITLE
Improve IA around all of HMDA content and tools

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1025]
We can move most of, if not all, content to ffiec.cfpb.gov ... along with our tools currently running on gh-pages (including API docs).

This will improve the overall UX for people doing anything with HMDA.

A quick thought (in no particular order):

- /
- /tools
  - /check-digit
  - /rate-spread
  - /file-format-verification
- /reports
  - /aggregate
  - /disclosure
  - /modified-lar
- /for-filers
  - /filing-instruction-guides
  - /lar-formatting-tool
  - /faq
  - /tech-preview
- /developers
- /blog

Does the app path need to change, /filing?

**Comment by designlanguage** [comment]
@awolfe76 - Most of this content is split up into the type of content, but "for filers" is split by audience. That makes the LAR formatting tool an outlier. I'd guess that many people would expect the LAR formatting tool to be under tools. To avoid confusion, how about we keep it split by content type? That would mean reframing "for filers" as "help" or "instructions". Even "instructions for filers" would be fine.

Also, does the current platform login (homepage) need to be lumped in with all this material or can it be separate like each of these other sections? I prefer separate, linked on this page, and maybe it becomes a banner at the top of the page during filing season. Interested to know your thoughts on this:

- /
- /platform
- /tools __- could be framed as supporting tools__
  - /check-digit
  - /rate-spread
  - /file-format-verification
  - /lar-formatting-tool
- /reports
  - /aggregate
  - /disclosure
  - /modified-lar
- /for-filers __-could be reframed as help or instructions for filers__
  - /filing-instruction-guides
  - /faq __- consolidate with knowledgebase?__
  - /tech-preview
- /developers
- /blog

**Comment by designlanguage** [comment]
I don't think the top nav of the platform should be conflated with the nav of the homepage. Using the USDS web standards for menus, that might look something like this:

![screen shot 2018-03-09 at 5 44 53 pm](https://user-images.githubusercontent.com/10562544/37233699-41cc8ef2-23c2-11e8-9688-bc34028d3ab5.png)

Three of the menus could have drop-downs (for where there are subsections). For example, that would allow you to navigate to a specific tool from the homepage.
