### ISSUE TITLE
Display more sensical content in Summary when request fails

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#1026]
Rather than displaying nothing for the values if a request to the summary endpoint fails, we should display a specific summary error. Implementation-wise this will probably be an error flag in the state that gets set by an action triggered on a 404.

**Comment by awolfe76** [comment]
@keileyo - Can you add any messaging you would like?

**Comment by keileyo** [comment]
The goal is to provide language that encourages the users who encounter this error message to try uploading their file again as that usually works to resolve the issue.  @colleenms thoughts on the message below?

"We're unable to return a summary of your filing at this time. **Please return to the homepage and upload your file again.**  You will be unable to sign your filing until you can review, correct and verify all edits as needed and a summary of your filing is generated.

**Comment by wpears** [comment]
So we're solving the issue causing lots of 404s here on the backend. I'm keeping this issue open because it's still valid, but we might want to alter the language, as requiring a re-upload in general probably isn't the optimal solution (summary 404s are generally rare and can usually be fixed with a refresh).
