### ISSUE TITLE
Add loading icon to signature component

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1062]
Add the loading icon beside the signature button and display it after someone clicks until we get a good response from the back-end.

[Signature component](https://github.com/cfpb/hmda-platform-ui/blob/4cc47a5b3414fe4ba6a632224186dd8dac799e20/src/submission/signature/index.jsx#L70-L75)

**Comment by wpears** [comment]
This is addressed in #1061
