### ISSUE TITLE
Space between words

### ISSUE THREAD

**Issue by jlnalcazar** [cfpb/hmda-platform-ui#1081]
On the [Dynamic National Loan-Level Dataset](https://ffiec.cfpb.gov/data-publication/dynamic-national-loan-level-dataset] page, the second line needs space between the word "and" and "borrower". 

![space between words](https://user-images.githubusercontent.com/42008406/43540047-9daf945a-9594-11e8-8e61-f54cf576dcfc.png)
@awolfe76

**Comment by awolfe76** [comment]
Closed by https://github.com/cfpb/hmda-pub-ui/issues/188.
