### ISSUE TITLE
Edit to Dynamic National Loan-Level Dataset

### ISSUE THREAD

**Issue by jlnalcazar** [cfpb/hmda-platform-ui#1082]
Here is a language suggestion for the [Dynamic National Loan-Level Dataset](https://ffiec.cfpb.gov/data-publication/dynamic-national-loan-level-dataset) web page. 

The dynamic files contain the national HMDA datasets for all HMDA reporters, modified by the Bureau to protect applicant and borrower privacy, updated to include late submissions and resubmissions. The dynamic files are available to download in a pipe delimited text file format. The dynamic datasets are updated on Mondays with HMDA submissions received through the previous Sunday night.

@awolfe76 @wpears

**Comment by awolfe76** [comment]
Closing, see https://github.com/cfpb/hmda-pub-ui/issues/189.
