### ISSUE TITLE
WIP - Websockets messaging 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-ui#1106]
Starting this to work out the UI messaging using websockets:

For a number of small files that go through the happy path, opening up websockets wont be necessary. In that case:
1) If happy path -  instead of the progress bar, we should use checkmarks similar to the progress bar across the top for upload, parsing & validating. 
- While the file is uploading, show "file uploading" and when it is complete, show "file uploaded" with a completed checkmark. 
- while file is parsing, show "checking file format" and when it is complete show "format check completed" with a completed checkmark
- when file is validating, show "validating edits" and when it is complete show "edits validated" with a completed checkmark. 
2) Open up the websockets connection after 10 seconds to start showing progress in a certain stage (so files that upload, parse and validate in < 10 seconds will not use websockets connection). 
- for all of the stages, what we want to show is the number of rows that has completed uploading, parsing or validating

3) investigations
- investigate whether we can include some language in the UI that appears if a file is stuck in a certain stage for an extended period of time (i.e. if its showing that parsing has been stuck on row 150/1000 for 30 seconds, include a message). The message could encourage the user to upload the file again. 
- investigate integration with back end that could allow the user to complete an action that triggers the back end to move past a stuck file

**Comment by wpears** [comment]
Technically, I think it makes sense to instantly open a WebSocket for all filings. Currently, the way we actually verify that a file has moved to a different stage/status is by polling the `/status` endpoint. This means making at least one and likely several requests to the backend, so we aren't really saving anything by avoiding a WebSocket, as these same updates would be sent through the socket (and in most cases more efficiently).

So I'd think we'd maybe want a separate progress bar for each stage (uploading, parsing, validating)
**Uploaded** |||||||||||||||||||||||||| ✔️||||||||||||||||||||||||
&nbsp;&nbsp;&nbsp;&nbsp; Parsing ||||||||||||||            21% **581/2767** rows&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|
             ...
This way we can give instant feedback at the process will seem faster and more interactive for everyone, even people whose file is validated in ~5s.

re: investigations, we'd certainly be able to show in the UI whether a file is stuck on a given row, though I think we wouldn't want to allow the user to affect the operation of the backend with any action other than reuploading. Indeed, if we're going to have some cutoff where we think a file is stuck, the backend should just bail with an error and the front-end can display that error ('Line xx failed to parse. Please ensure this line is formatted correctly and re-upload your file').

**Comment by jmarin** [comment]
+1 on opening a WS connection as soon as is possible. Initially, what we will be able to offer is _"real time"_ updates being pushed from the server as they happen through a single `ws` connection, updating the status codes of the application (with their description). Row counters will come later, as that is more involved
