### ISSUE TITLE
Add note about edits that aren't being checked on the beta platform

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform-ui#1109]
![image](https://user-images.githubusercontent.com/41752348/48028945-f1630d80-e11a-11e8-8e19-3b281488096e.png)

Language: "Please note: Edits V625-627, Q600, Q603, Q604, and Q634-640 are not currently implemented into the beta platform. These edits will be added when the final platform is released in 2019."

**Comment by awolfe76** [comment]
Also, see https://github.com/cfpb/hmda-platform-ui/pull/826/files for updates from the last beta period.

**Comment by keileyo** [comment]
@awolfe76 @chynnakeys where does it make sense to add this language? I was thinking that it could be a banner on the S/V, Q and MQ edits pages.

**Comment by awolfe76** [comment]
Closed by #1119
