### ISSUE TITLE
Apply beta content in the UI

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-ui#1116]
Bring back the content used during the beta period last year to indicate that the filing period is not open and that this is just a testing period. 

The original content is captured in #810, and the updates should be to the dates. Anywhere the previous content used January 1st, 2018 update to January 1st, 2019 and update the homepage "...filing period for HMDA data collected in 2017" to "....filing period for HMDA data collected in 2018."

**Comment by awolfe76** [comment]
Closed by #1119
