### ISSUE TITLE
Include banner on edits page about descriptions not being available

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform-ui#1125]
There should be language informing users know that edit descriptions will not be available on the beta platform, but will be updated soon. 

"The initial release of the beta platform will not feature edit descriptions. This addition will be included in the January 1 release of the platform. In the meantime, if you have a question about an edit, you can view all edit descriptions oin Section 5.3 of the 2018 Filing Instructions Guide, found here (with https://s3.amazonaws.com/cfpb-hmda-public/prod/help/2018-hmda-fig-2018-hmda-rule.pdf hyperlinked)"

**Comment by keileyo** [comment]
I've updated this slightly: 

"The initial release of the beta platform will not feature the detailed edit descriptions and tables, but this feature will be added soon. If you have a question about an edit received on the beta platform, you can view all edit descriptions in Section 5.3 of the [2018 Filing Instructions Guide](https://s3.amazonaws.com/cfpb-hmda-public/prod/help/2018-hmda-fig-2018-hmda-rule.pdf).  Please consult your system of record to view the relevant data about the loan(s) or application(s)."

@jmarin - can you let us know if the actual description of the edit will be returned (and therefore just the detailed table is missing) or if both the description & detailed table will come in a future release. We may need to wordsmith this a little further if we are in fact getting the descriptions.

**Comment by awolfe76** [comment]
We have content now that says 

`Edits V625-627, Q600, Q603, Q604, and Q634-640 are not currently implemented into the beta platform. These edits will be added when the final platform is released in 2019.`

Can this new content just go along with it?

**Comment by keileyo** [comment]
@awolfe76 it can, but another idea would be to have it appear on the screen only if/when a user actually gets the edits to better draw attention to it.  Totally understand we are super short on time, so implement how you see fit. If we do need to include it in the banner, i would suggest making it a separate paragraph from the paragraph about the missing edits.

**Comment by awolfe76** [comment]
We'll just combine these messages, but still separate paragraphs. Don't want to get into adding logic for something that is going away soon.

**Comment by wpears** [comment]
Closed by #1130
