### ISSUE TITLE
Screenshots of platform for clearance

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-ui#1126]
@awolfe76 and @wpears as you are working on getting the platform integrated & deployed locally with all of the beta content, can you please take & send me screenshots of the major pages in the platform. I need them to do a quick clearance. 

- login
- homepage after login
- S/V edits
- Q/M
- submission page

**Comment by awolfe76** [comment]
No problem. We'll probably need to wait until we get some more integration with the back-end done first, to make sure that we have it correct.
