### ISSUE TITLE
Trigger new submission on re-upload

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#113]
Re-uploading (or perhaps clicking a button that is part of the component that says re-upload) needs to trigger the creation of a new submission which should update the app's state.

The app could wait for the POST's response which will include the submission number and status/status code from which it could both `history.replaceState` and set the submissionContainer's state.

**Comment by wpears** [comment]
#159 introduces a "refile" button that is a simple link to the next submission (which would be created server-side after incepting the request). However, it's still probably necessary to cause **reuploading via the upload component** to trigger a new submission and to `replaceState` to this submission

**Comment by awolfe76** [comment]
Closing. Being discussed in #214. Also in #205 and https://github.com/cfpb/hmda-platform/issues/535.
