### ISSUE TITLE
Get available institutions

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1134]
Now that #1132 is merged, we can get the list of institutions (`lei`s) to make the correct API calls for the institution and filing data.

_This should finish removing the [mocked API responses](https://github.com/cfpb/hmda-platform-ui/blob/b48869078803c224b1ea519ff6ac5b89f95e6110/src/api/api.js#L3-L13)._

**Comment by wpears** [comment]
Closed by #1142
