### ISSUE TITLE
Creating filing when a filing already exists 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-ui#1148]
Upon loading, it seems like the web page tries to create a new filing for 2018, regardless of whether one exists already which is an illegal API call and causes a 400 error.  It's first doing a `POST` to create a new filing, when it should first try a `GET` to see if a filing already exists and only creating the post if the filing does not exist. 

![image](https://user-images.githubusercontent.com/13036571/49092775-bb540d80-f230-11e8-9643-6bc7832d207a.png)

@wpears can you take a look at this today?

**Comment by wpears** [comment]
:eyes:

**Comment by wpears** [comment]
Closed by #1151
