### ISSUE TITLE
Replace 2017 FIG Link with 2018 FIG Link when edits appear

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform-ui#1152]
The sentence should say: "The uploaded file is not formatted according to the requirements specified in the Filing Instructions Guide for data collected in 2018 incorporating the 2018 HMDA Rule" with the 2018 FIG linked: https://s3.amazonaws.com/cfpb-hmda-public/prod/help/2018-hmda-fig-2018-hmda-rule.pdf 

![image](https://user-images.githubusercontent.com/41752348/49112830-ce330600-f261-11e8-8b81-bb44cccf4e8e.png)

**Comment by awolfe76** [comment]
Closed by #1154
