### ISSUE TITLE
Visual elements on the Syntactical and Validity edits screen

### ISSUE THREAD

**Issue by MattPerrine** [cfpb/hmda-platform-ui#1153]
There are a lot of visual elements competing for users attention on this page; as a result the user may not see the yellow/orange banner immediately. In the moment their eye is likely drawn to the 'Syntactical and validity edits (0 found) message and the green 'Your data did not trigger any syntactical or validity edits' banner. We may need to think about a different location for the yellow/orange banner info.

![image](https://user-images.githubusercontent.com/25694077/49113303-30403b00-f263-11e8-8091-2bbeff70b0d8.png)

**Comment by wpears** [comment]
Closed by #1212
