### ISSUE TITLE
Let filers know we're getting the edits

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1169]
#1165 blocked navigation until the edits were fetched, but it also shows the spinner without any messaging about what's going on (the edits are being fetched). It would be nice to add some content with this saying that. Just something simple, eg "Getting edits now".

**Comment by keileyo** [comment]
Agree! How about "Retrieving your edits now"

**Comment by awolfe76** [comment]
Closed by #1176
