### ISSUE TITLE
CSS - submission page headings and content

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1170]
The IRS, Summary, and Signature headings and content are all different; widths, sizes, etc. These should all be made to match the Signature block.

![submission](https://user-images.githubusercontent.com/2932572/49222691-88ce2000-f3aa-11e8-84c2-e67c0d5bf474.png)

**Comment by MattPerrine** [comment]
Do we want to remove the 2nd 'HMDA test filing accepted!' banner? I'm noticing a 2nd banner 'Your filing is ready to be signed and submitted' here too: 

![image](https://user-images.githubusercontent.com/25694077/49231269-9641d500-f3bf-11e8-988a-0c5d150fd925.png)

**Comment by awolfe76** [comment]
@MattPerrine - we might do that. We had it twice because of the space taken up by the IRS and Summary information. So it would be obivous immediately and then just before the Signature block. Not showing the IRS and Summary information, for now, makes it seem a bit much but that probably won't be the case when we do start showing those.

If you want to create a new issue we can revisit as those API endpoints get build.

_Edit: I say we might want to do that because the IRS will likely not appear on this page. We should see what it looks like with the Summary information._

**Comment by MattPerrine** [comment]
@awolfe76 - Makes sense. Keiley and I just talked about this actually. Should we remove the IRS blurb on this page now (while in Beta) and we can open a separate ticket on where to put the IRS when we're live?

**Comment by awolfe76** [comment]
We could remove the blurb, but I thought the reason for having it now was to basically give filers a heads up for whats coming? Could be remembering wrong now.

Either way I definitely think we can open an issue for where the IRS will go.

**Comment by keileyo** [comment]
@awolfe76 i think it does actually make sense to remove it. If I'm understanding correctly, the IRS will not be generated AFTER the signature and only as a CSV, so i think think it really even needs a space in the UI. What makes most sense to me is just to include a line in the Green submission box, perhaps underneath the receipt hash stating "Your institution register summary can be downloaded [here]."

**Comment by awolfe76** [comment]
At this point I think we'd be better to spin the IRS stuff off into another issue. I don't think its blocking the beta release, so we can get to it soon.

**Comment by awolfe76** [comment]
Closed by #1172
