### ISSUE TITLE
Make the v2 branch the master branch

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#1171]
To get ready for the beta release we should make the v2 branch the master branch. A few things to do:

- [ ] create a `v1.x` branch based on current `master` (or update it if it already exists)
- [ ] do a PR from the current `v2` to `master` (this has all been reviewed and should just be a merge unless there are conflicts)
- [ ] update the `Jenkinsfile` to change any case of `v2` to `master`
- [ ] any updates for previous build and deploy process (so it deploys `v1.x` instead of `master`)

Anything else @kgudel?

**Comment by kgudel** [comment]
I think that this all looks good, the `Jenkinsfile` changes will be minor, only 3 places I think.

(Also, I'm not sure we even need to update the previous build process since we won't be using it anymore for these apps. I guess not hard though and doesn't hurt.)

Anyway, LGTM

**Comment by awolfe76** [comment]
> (Also, I'm not sure we even need to update the previous build process since we won't be using it anymore for these apps. I guess not hard though and doesn't hurt.)

Well, we won't be using it for `v2` but, we may have to redeploy `v1.x` of `hmda-platform` and `hmda-platform-ui` in case bugs are found there by late filers or someone needing to refile. Yeah, we're probably pretty safe but should be ready.

I don't think we'll ever have to redeploy `v1.x` for the other UI repos, homepage, tools, and pub, though. No one should use those.

**Comment by awolfe76** [comment]
Closed by #1222
