### ISSUE TITLE
Increase size of check boxes

### ISSUE THREAD

**Issue by MattPerrine** [cfpb/hmda-platform-ui#1174]
Can we increase the size of check boxes on the platform.

Current check box size looks like this:
![image](https://user-images.githubusercontent.com/25694077/49239279-56371e00-f3d0-11e8-9c9a-cc229f227981.png)

Previously it was larger and easier for user to see, like this:
![image](https://user-images.githubusercontent.com/25694077/49239298-6d760b80-f3d0-11e8-9fc4-7fa39a2c9957.png)

**Comment by awolfe76** [comment]
I was actually hoping to avoid this. It's a chunk of styling that isn't really all that necessary. I tend to want to just leave it alone. That said, there may be other options to look into if it is a problem for people.

**Comment by MattPerrine** [comment]
An alternative could be allowing the user to click the checkbox or click on the actual sentence to check the box. Not sure the LOE of that option.

**Comment by awolfe76** [comment]
Turns out that was already the case, both the label and input were clickable. 😄

#1181 makes it more obvious.

**Comment by awolfe76** [comment]
Closed by #1181
