### ISSUE TITLE
Quality Edits Screen - 'Your File Has Quality Edits' banner missing

### ISSUE THREAD

**Issue by MattPerrine** [cfpb/hmda-platform-ui#1175]
The 'Your File Has Quality Edits' banner is missing from the current quality edits screen. This banner told the user what they needed to do if their file had quality edits and gave the a link to reload an updated file. Are we able to get this added back?  

![image](https://user-images.githubusercontent.com/25694077/49239532-0016aa80-f3d1-11e8-9881-a326c5b74e47.png)
![image](https://user-images.githubusercontent.com/25694077/49239563-10c72080-f3d1-11e8-8bdc-07ced62c5565.png)

Previously a user would see a banner like this at the top and bottom of the screen:

![image](https://user-images.githubusercontent.com/25694077/49239440-c6de3a80-f3d0-11e8-83ea-9b0760dc0faa.png)

**Comment by awolfe76** [comment]
Closed by #1196
