### ISSUE TITLE
Remove content about edits details from the beta edits banner

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-ui#1198]
Now that we do have edits details, remove the following content from the beta banner edits banner: 

"The initial release of the beta platform will not feature the detailed edit descriptions and tables, but this feature will be added soon. If you have a question about an edit received on the beta platform, you can view all edit descriptions in Section 5.3 of the 2018 Filing Instructions Guide. Please consult your system of record to view the relevant data about the loan(s) or application(s)."

**Comment by wpears** [comment]
Closed by #1212
