### ISSUE TITLE
Update UI to grab end date from latest endpoint

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform-ui#1201]
The backend provides enddate on the `/latest` endpoint but the UI is showing December 31st, 1969

<img width="1440" alt="screen shot 2018-12-07 at 9 21 48 pm" src="https://user-images.githubusercontent.com/44377678/49680753-4bcaf300-fa66-11e8-99ab-022948f23c43.png">

**Comment by wpears** [comment]
Closed by #1202
