### ISSUE TITLE
Revert beta code changes

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#1210]
On a branch we'll need to revert the changes introduced in https://github.com/cfpb/hmda-platform-ui/pull/1119 and https://github.com/cfpb/hmda-platform-ui/pull/1130.

There will be some additional work on top of the reversions to parse out the status of the IRS Report and the Summary in the 2018 platform.

**Comment by keileyo** [comment]
We will need to make a few changes more than just reverting back to the 2017 submission platform content. Specifically:
- Update /filing/2018 header to "Get started filing your 2018 HMDA data"
- Updating any 2017 to 2018 throughout
- Updating the banner that says the filing period is closed to one that says the filing period is open

**Comment by awolfe76** [comment]
@keileyo - I think your list is all covered by what @wpears mentions.

Do you see 2017 mentioned anywhere in the app? Something we've missed?

The banner update should happen automatically based on the date, but definitely something we should double check Jan 1 or so.

**Comment by keileyo** [comment]
@awolfe76 i think you're right. as long as the banner updates and has the correct dates when we should be ok.

**Comment by awolfe76** [comment]
@wpears - I think I have the IRS content reverted in a coming PR, just a heads up.
