### ISSUE TITLE
IRS content & placement

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-ui#1214]
This year, the IRS will not be generated in the UI for each submission. It should only be offered as a CSV download AFTER a filing is signed and submitted. We need to determine the best way to make this available on the submission page. I see a couple of options:

1) Keep the IRS content/text where it is, and include something like:

During the 2018 filing period, the IRS will be made available in the HMDA Platform after signing and submitting your HMDA data. The Institution Register Summary will not be available immediately. Please check back in (a day, a week?*) to review your IRS. 

[Link to IRS]

*The language here is somewhat dependent on whether we actually get IRS done before 1/1 or are working on it in the first week of Jan. 

2) Move the content to below the green submission acceptance box w/ a similar message to what was created above. 

@awolfe76 @wpears thoughts? other ideas?

**Comment by awolfe76** [comment]
I'm going to stick with option 1 for now. We can definitely come back to this if filers are finding it difficult to find/use.

There are other places we could make this available too, eg the institutions page (logged in home page).

**Comment by keileyo** [comment]
Edited to change Institution Register Summary to IRS in the second sentence. 

ok sounds good to me. perhaps the language below is good enough for now (while we are still unclear on when IRS will be done, and can be cleaned up once we have more info): 

During the 2018 filing period, the IRS will be made available in the HMDA Platform after signing and submitting your HMDA data. The IRS will not be available immediately. Please check back later to access your IRS. 

[Link to IRS]
