### ISSUE TITLE
Entity Stream Truncation

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform-ui#1231]
This is related to https://github.com/cfpb/hmda-platform/issues/2410

When uploading a large file (1M row file) from the UI, the request seems to get cancelled in the middle and backend receives error `Entity Stream Truncation`. If we upload a file directly to the backend API (bypassing UI), then we do not receive `Entity Stream Truncation` error. 

This might have something to do with the Nginx timeouts.

**Comment by zencircle** [comment]
Ambassador logs do not show any 4XX when there is a failure.  hmda-platform-ui ngnix settings 
```
client_body_buffer_size  16k;
  client_header_buffer_size 1k;
  client_max_body_size 5m;
  large_client_header_buffers 4 8k;
  client_body_timeout 60s;
  client_header_timeout 60s;
  send_timeout 60s;
```
Adding ambassador hmda-platform-ui timeout to 40s does not change in the behavior
