### ISSUE TITLE
/filing/2018 without the trailing / redirects to the 2017 login page 

### ISSUE THREAD

**Issue by keileyo** [cfpb/hmda-platform-ui#1232]
https://ffiec.cfpb.gov/filing/2018 redirects to https://ffiec-auth.cfpb.gov/auth/realms/hmda/protocol/openid-connect/auth?client_id=hmda-api&redirect_uri=https%3A%2F%2Fffiec.cfpb.gov%2Ffiling%2Foidc-callback&response_type=id_token%20token&scope=openid%20profile&state=9786ec07da264ff99296f5a4a422e2c8&nonce=883a91322ae845759add038d0021259

I assume this is redirection to 2017 since 2017 filing is still at /filing/  - can we force this to redirect to just the https://ffiec.cfpb.gov homepage?

**Comment by awolfe76** [comment]
@zencircle - this seems to be caused by something higher up.

**Comment by zencircle** [comment]
Add explicit path and that seemed to have fixed the issue
![image](https://user-images.githubusercontent.com/25303681/50693079-eab22300-1003-11e9-83b5-f996680f5094.png)

**Comment by awolfe76** [comment]
Awesome. Thanks, @zencircle.
