### ISSUE TITLE
Favicon is not Displaying on Production Site

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform-ui#1247]
This issue is relevant for all of the -ui applications in production except for the` hmda-platform-tools` where the favicon is being fetched and displayed properly.

The favicon is currently displaying properly in development.

**Comment by wpears** [comment]
Fixed by https://github.com/cfpb/hmda-platform-ui/commit/d0396ce2cb92e89f480fa03ec0e9f4c7ce7bb653
