### ISSUE TITLE
Determine file extension using magic bit instead of file name

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform-ui#1249]
It would be good if the front end can determine the file type using magic bit (https://en.wikipedia.org/wiki/Magic_number_(programming)#Magic_numbers_in_files) instead of determining the file type based on the file name extension. If react doesn't support this, we can make that determination on the back end by providing an endpoint but that would require full upload of the file prior to making that determination.

**Comment by meissadia** [comment]
Articles
- https://medium.com/the-everyday-developer/detect-file-mime-type-using-magic-numbers-and-javascript-16bc513d4e1e

- https://stackoverflow.com/questions/18299806/how-to-check-file-mime-type-with-javascript-before-upload

Libraries
- https://github.com/sindresorhus/file-type
- https://github.com/LarsKoelpin/magic-bytes
