### ISSUE TITLE
Formatting Error Language Change: "is not a non-empty string or NA"

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform-ui#1282]
Field "is not a non-empty string or NA" messages occur a user types “na” or “Na” instead of NA or a user has a blank, a number with a blank (4 ), or a symbol (other than a decimal) in an alphanumeric field that does not accept anything other than expected values. 

Change display from 
![image](https://user-images.githubusercontent.com/41752348/65899231-ce7cc000-e3a2-11e9-9d51-e050131a7cd6.png)
to 

![image](https://user-images.githubusercontent.com/41752348/65899294-f66c2380-e3a2-11e9-87bb-c9c5c3af255d.png)

Attached is a test file that displays this type of formatting error upon upload. 
When na is used: 
[Bank1_is not NA (lowercase).txt](https://github.com/cfpb/hmda-platform-ui/files/3672345/Bank1_is.not.NA.lowercase.txt)

When field is blank: 
[Bank1_is not a nonempty string.txt](https://github.com/cfpb/hmda-platform-ui/files/3672351/Bank1_is.not.a.nonempty.string.txt)

**Comment by PatrickGoRaft** [comment]
@chynnakeys  Fixed #1285

**Comment by chynnakeys** [comment]
LGTM in prod beta
