### ISSUE TITLE
Edits: Show the values entered as opposed to “invalid input” with edits.

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform-ui#1285]
Currently, if a value is invalid for a data field, the message “invalid input” is displayed. In the case below, Automated Underwriting System Result: 1 was entered as 25, which is not an accepted value. Instead of displaying “invalid input”, edits should display the input that the user entered.

![image](https://user-images.githubusercontent.com/41752348/65912453-c2522c00-e3bd-11e9-8e4a-cdce39a5b09b.png)

**Comment by PatrickGoRaft** [comment]
@chynnakeys could you provide a sample submission file to replicate

**Comment by chynnakeys** [comment]
@PatrickHSI 
[Bank1_1_v696_2 invalid input.txt](https://github.com/cfpb/hmda-platform-ui/files/3682673/Bank1_1_v696_2.invalid.input.txt)

**Comment by omnipresent07** [comment]
Closed via https://github.com/cfpb/hmda-platform/pull/3217
