### ISSUE TITLE
Edits: AUS and AUS result values should be displayed as (Blank)

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform-ui#1286]
When there's nothing entered in the field, currently 0's are displayed. Instead of 0's, the message (Blank) should be displayed. 

![image](https://user-images.githubusercontent.com/41752348/65912510-d9911980-e3bd-11e9-8c36-869b63e0e963.png)

**Comment by PatrickGoRaft** [comment]
@chynnakeys could you post a sample submission file to replicate this

**Comment by chynnakeys** [comment]
@PatrickHSI 
[Bank1_1_v696_2 ck.txt](https://github.com/cfpb/hmda-platform-ui/files/3682662/Bank1_1_v696_2.ck.txt)

**Comment by PatrickGoRaft** [comment]
I believe we can take care of this on the front end.

**Comment by chynnakeys** [comment]
LGTM
