### ISSUE TITLE
Authentication for quarterly filing

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform-ui#1297]
When quarterly filing is open, only selected institutions should see the option to submit a filing for a quarter.

**Comment by omnipresent07** [comment]
`/filing/institutions/<lei>/year/<year>` should now return a new key `quarterlyFiler` with values true/false. Front end should use this flag to show/not show quarterly Filing. This is covered in this PR in the backend https://github.com/cfpb/hmda-platform/pull/3246/files

**Comment by ericspry** [comment]
Moved to hmda-frontend #77 https://github.com/cfpb/hmda-frontend/issues/77
