### ISSUE TITLE
Change messaging for the platform signing page based on the year

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform-ui#1301]
The signing page for the platform reads the following irrespective of the filing year. 

> Loan amounts in the IRS are binned and disclosed in accordance with the 2018 HMDA data publication policy guidance. An overview of the policy guidance can be found in this executive summary.

- [x] It should be updated based on the filing year

- [x] The link for the IRS report goes to 2018 S3 bucket. Rather it should go to 2018 only when the submission is for 2018 and should go to 2019 bucket when the signing is for 2019

**Comment by PatrickGoRaft** [comment]
Note: 
 The guidance document does not  change annually so that portion of the page will still reflect 2018. Please keep this in mind during coe review.
