### ISSUE TITLE
Maintenance Image/Environment Variable #1318

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform-ui#1303]
We would like a way to have a configurable environment on the platform-ui so that we can turn the variable on/off and based on the on/off value it would show a message. 

This would be good for us to have when we perform maintenance on the platform.

**Comment by wpears** [comment]
Once built, the frontend is a static app that can't access environment variables. If we want to be able to show a real time status or render different content based on a flag, we should probably have a status endpoint where a backend service can read envvars/hit a database.

**Comment by omnipresent07** [comment]
The backend can't provide this status message since when we do cluster maintenance backend isn't reliable to remain up. I'd like to propose having the frontend read a static (publicly available) file from S3 that contains JSON keys. Based on the values of these JSON keys (true/false), the front end would display specific messaging. This way when the team is doing maintenance, we can simply update the S3 file. Additionally, this file could also contain keys for specific messaging we want turned on/off during filing season.

**Comment by meissadia** [comment]
We will host a config file on Github that frontend repos will be able to read on load.  

Config file will contain
- announcement (0 or 1 message)
- default year for header filing link (2019 starting Jan 1, 2020)
- available filing years (i.e. [2019, 2018] starting Jan 1, 2020)

**Comment by meissadia** [comment]
Since this file will be shared across a number of apps I'm thinking it should live in [HMDA Platform](https://github.com/cfpb/hmda-platform)

**Comment by meissadia** [comment]
- [x] Add prod/dev config file to Platform repo (https://github.com/cfpb/hmda-platform/pull/3345)
- Update frontend repos
  - [x] Platform UI (https://github.com/cfpb/hmda-platform-ui/pull/1329)
  - [x] Homepage (https://github.com/cfpb/hmda-homepage/pull/112)
  - [x] Data Browser (https://github.com/cfpb/hmda-data-browser/pull/217)
  - [x] Publication (https://github.com/cfpb/hmda-pub-ui/pull/329)
  - [x] Platform Tools (https://github.com/cfpb/hmda-platform-tools/pull/226)

**Comment by meissadia** [comment]
Config file has been merged in `hmda-platform`, the sub-PRs are no longer blocked.  

This is ready for review

**Comment by wpears** [comment]
Everything is merged in here
