### ISSUE TITLE
Quality and Macro quality edits are falsely verified in beta

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-platform-ui#1321]
A user has reported being unable to verify their macro edits. Upon further inspection, the macro and quality edits are being set to false, although on the UI they show as verified.

**Comment by omnipresent07** [comment]
This is reproducible when the lar file contains no Quality or Macro errors.

**Comment by omnipresent07** [comment]
This is not fixed fully with the PR. Attached is a sample file that can be tested. 
[Bank0_clean_1_row no MQ.txt](https://github.com/cfpb/hmda-platform-ui/files/3876741/Bank0_clean_1_row.no.MQ.txt)

**Comment by omnipresent07** [comment]
This is an issue on the backend as well - https://github.com/cfpb/hmda-platform/issues/3272
