### ISSUE TITLE
master should default to 2019

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform-ui#1323]
The `master` branch at the moment is doing a force redirect to 2018. This should not be happening in the `master` branch. Can we make it such that:

`master` branch defaults to 2019 (will be deployed to beta until we're ready to open 2019 in production)
`remote-2019` branch defaults to 2018 and remains in-sync with `master` (will be deployed to main production until we're ready to open 2019 in main production)

**Comment by meissadia** [comment]
PR for getting `master` to default to 2019.

`remove-2019` branch has been updated to reflect current `master` changes
