### ISSUE TITLE
Warnings in the UI

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#134]
@wpears, after #132 I'm noticing a few warnings in the UI - 

`app.min.js:1510 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the EditsContainer component.`

`app.min.js:1510 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the IRS component.`

It does prevent the IRS report from rendering, even though the edits do.

These happen when running master now. Sorry I didn't notice them earlier.

**Comment by wpears** [comment]
Fixed by #135
