### ISSUE TITLE
Add dropdown/picklist feature for responding to macro edits in the submission system

### ISSUE THREAD

**Issue by debseidner** [cfpb/hmda-platform-ui#141]
Instead of free-form text, we want filers to pick the reason for the macro edit appearing from a drop down or pick list. 

There should be the ability to pick more than one reason for each macro edit. Pilot testers noted that they may need to pick two reasons on occasion. For instance, volume could be high because there was (1) an uptick in refinancing because of low interest rates and (2) the FI could have bought another FI and so the institution in this case would want to be able to choose these two reasons.

Each macro edit will have a separate list of drop down choices. The list is not the same for every macro edit.

**Comment by debseidner** [comment]
Continuation of #45

**Comment by awolfe76** [comment]
Is there an option of "other" which then shows a text area? In case one of our options don't apply?

**Comment by debseidner** [comment]
@awolfe76 Yes, there should be an option for other that when selected, opens up free form text.

**Comment by wpears** [comment]
Closed by #170
