### ISSUE TITLE
Update API for home page

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#143]
It looks like the API for the home page data, the list of institutions is still calling `/api/institutions`.
It should be calling `/institutions/period/<period>` to match what's in https://github.com/cfpb/hmda-platform/issues/331.

**Comment by wpears** [comment]
Continue to track cfpb/hmda-platform#331, on this; there might be more general API work to come

**Comment by awolfe76** [comment]
Also, https://github.com/cfpb/hmda-platform/pull/411

**Comment by awolfe76** [comment]
Closing, we can come back to this about https://github.com/cfpb/hmda-platform/pull/422 get sorted out.
