### ISSUE TITLE
Integrate q029 and q595 into quality edits

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#144]
Unless there is a compelling reason to keep these in their own components, I think they should just be quality edits. This will require restating the call to actions somewhat, but it isn't too much of a stretch.

Also, if we're not, in general, allowing data input other than macro verification, we shouldn't get in the habit of building ad hoc components that will need their own persistence layer/entangle us with the FI's system of record.

**Comment by wpears** [comment]
This would also close #137 and #136

**Comment by lesgou** [comment]
@wpears No compelling reason for their own components. The instructions for should be modified, for example, Q595 should be modified to instruct filers that checking the box indicates they have a branch in that msa.

**Comment by awolfe76** [comment]
I talked with @lesgou a bit. I think Q029 can be merged with the other quality edits, it would have a "verify all" option the same as the other quality edits. But Q595 should probably remain in its own component. It still has a line-by-line verification.

Also, I think the quality edits (except for 595) should be broken out into a `EditsQuality.jsx` component. These edits are different enough from syntactical and validity to justify their own component.

**Comment by awolfe76** [comment]
Closing in favor of #157
