### ISSUE TITLE
Grouping of edit reports

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#15]
Pilot grouped the edits by type, syntactical and validity, quality and macro, and MSA and IRS. 

Several times in the "summary and findings" document users mention that it would be nice, in some cases, to see the reports by loan number. They talk about it mostly for as an export option but do we think that this might make sense in the UI as well?

@debseidner @wpears @benguhin

**Comment by benguhin** [comment]
:+1:  I think this is definitely worth exploring, especially in terms of whether we should include methods for sorting and filtering, and how we display all results (as noted in #18)

**Comment by wpears** [comment]
Yeah, the groupings in Pilot seem to make the most sense only if you're familiar with the reg. Whereas users probably just want to see what's wrong with each entry and how to fix it. Honestly I think syntactical/validity/quality edits should only be secondary groupings or filter options. (Click to show only quality edits, etc).

**Comment by awolfe76** [comment]
I agree, I think trying this as grouped by loan, row by row, makes a lot of sense.

@debseidner any thoughts?

**Comment by debseidner** [comment]
I think it is fine to group by loan number within each category, meaning for syntactical and validity edits, you can group the results by loan number. But, I don't think it makes sense to group them across syntactical, validity and quality. For instance, it doesn't make sense for a financial institution to start working on quality edits when they have basic information wrong with their data, which is what the syntactical and validity edits do - make sure the data has all the right valid values and formats.

Also, within quality edits, the financial institutions need to start responding to why certain edits came up so if the data is not clean to begin with, they will end up re-doing that step over and over and get frustrated having to keep putting in the same answers each time.

The MSA reports may go away but probably worth rethinking how to display the IRS Report, which is a full summary of what has been loaded to file.

**Comment by debseidner** [comment]
I should add that it might make sense to have a way to download all the edits for a single file - syntactical, validity, quality, macro by loan number when the edits are run originally - so if you wanted to see all your edits and work on them offline, you can but then still think it makes sense to make financial institutions fix syntactical and validity before displaying more in the online tool.

**Comment by awolfe76** [comment]
We'll start by grouping the results by loan number, within each section, while giving the ability to sort/filter in other ways (by edit).
