### ISSUE TITLE
Maybe use mixins?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#154]
Using #153 as an example (there maybe other cases), we could possibly use [mixins](https://facebook.github.io/react/docs/reusable-components.html#mixins) to simplify the code.

We could break out edit components a little more, one component for each edit type, and use mixins when needed. This may save us from some of the logic used to render several edit types within one component.

@wpears

**Comment by wpears** [comment]
Closing until a concrete issue arises, _ie_ "Use mixins for **x** purpose in **y** components"
