### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#155]
We're going to be branding the UI as FFIEC. We can use this https://standards.usa.gov/ to help.
- uses Sass instead of Less
- different "style guide", USDS instead of CFPB.

**Comment by wpears** [comment]
I have some reservations about this; will fill in more after a discussion on 7/6.

**Comment by wpears** [comment]
Ignore the above; full speed ahead

**Comment by awolfe76** [comment]
Breaking this into a few chunks (a few PRs):
- [ ] general clean-up to get ready
  - remove less and add sass, remove cf- dependencies, add uswds dependency, setup build
- [ ] begin to apply new styles
