### ISSUE TITLE
Use a local npm cache tracker

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#158]
Things like [shrinkpack](https://github.com/JamieMason/shrinkpack) or [npm-ducttape](https://github.com/DeadAlready/npm-ducttape) which allow mirroring your dependencies into a local npm cache; preventing needless reinstalls during CI.

Checks in tarballs to Git, but this shouldn't be too much of an issue, as updates will just give binary file updates which don't really clog PR review.

Especially makes sense in docker installs, as once the code is pulled from the repo, no more network activity is required to build the image.

**Comment by awolfe76** [comment]
@wpears - do you still want this open?

**Comment by wpears** [comment]
Yeah, I'll get around to this eventually ;)
