### ISSUE TITLE
Ability to download the full report

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#17]
In the Pilot "summery and findings" doc there is talk about  the ability to see and download a full report at the end of the process, the full audit trail listing all of the errors that occurred, the fixes, etc.

**Comment by benguhin** [comment]
+1

**Comment by debseidner** [comment]
and should also include all the quality and macro quality responses that were inputted into our system

**Comment by awolfe76** [comment]
We are going to build the download feature, more issues can be created when the work begins.
