### ISSUE TITLE
Paging vs infinite scroll

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#18]
Instead of paging maybe we try a form of infinite scroll, something like "view 10 more" and/or "view all". These can be made smart enough based on total number of results. For example, if the default is to show 10:
- and only 11 (we pick the number) are returned, just show them all
- and 21 are returned only should the "view all" button

**Comment by benguhin** [comment]
This would be for the edit results? It could also be helpful to have a method of sorting or filtering to help the user address certain types of errors first. I love the idea of smart "view more" button, though pagination or showing all the results might be better for this case (I'm not sure)

@debseidner how do you expect users will interact with these results?

**Comment by wpears** [comment]
Yeah, being able to display all the edits on the same page would be pretty nice. We'd definitely need "Showing 10 out of 54 edits" or something along those lines along with the view more and view all buttons so people know what they're looking at/where they are

**Comment by wpears** [comment]
Also, I think we should pick a fairly large maximum until this mechanism comes into play at all. Maybe into the hundreds, depending on the row height/line height of the results. Reducing the number of interactions to get at the data is typically a win

**Comment by awolfe76** [comment]
:+1: on the "large maximum until this mechanism comes into play at all". We can use an expand/collapse per row, maybe even have the first one (or a few) expanded from the start to make it more obvious.

**Comment by debseidner** [comment]
I like the idea of the show more and only showing 10 edit errors at a time but maybe combined with the loans in #15, you show the loan numbers and a show more to see more loans with errors unless you mean the show more under a specific loan number, which would work fine too. Does it make sense to have a toggle at the top so the person can change the view wanted - like if someone wants to see by loan, the person chooses that or if another person wants to see by edit error, that person clicks on the toggle of by error. You could also consider a "Show me the quality edits" on the syntactical and validity tab if we go with that in which someone could see those if wanted but not try to clear them yet (so display only).

In terms of interacting, I think people get overwhelmed seeing a lot of errors at once and have to scroll through them so I think the see more would help. I think there were issues with having multiple pages of loans with errors on the quality edits as we saw concerns from the users that they had to page through all of the pages to verify that the error exists. I think you'll have users like it either way - all displayed or all collapsed.

**Comment by awolfe76** [comment]
Closing, we'll start with the idea of infinite scroll. More issues can be created when the work begins.

**Comment by benguhin** [comment]
One note as we're closing is that infinite scroll for hundreds of entries would probably suck for the user. I think it's a great way to manage the default screen height when there are 30-120 entries, but as it gets higher and into the thousands pagination is going to provide a much more controllable interface.

I think it's a cool responsive approach, though:
Less than 30: no collapsed entries
30-120: Collapse everything after the first 30 with a link that says "View 10 More / View all"
120+: Pagination (we have a [pattern for this](http://cfpb.github.io/cf-pagination/docs/) in capital framework)

**Comment by awolfe76** [comment]
Thanks @benguhin. Nice idea.
