### ISSUE TITLE
Update /components/ValidationProgress.jsx to show/hide messages

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#192]
Right now ValidationProgress.jsx shows all messages:

```
parsing started
parsing complete
validation started
validation complete
```

We should hide the "started" messages when the step is complete.

See [this comment](https://github.com/cfpb/hmda-platform-ui/pull/186/files/f478bd05cde17610786f2b0c631de0ec4a4386a0#r75295661) in the earlier PR.

**Comment by wpears** [comment]
I can think about some other designs where the started/complete messages are on the same line and we gray out "started" once complete is available.

```
Parsing started...            Parsing complete
Validation started...
```

**Comment by awolfe76** [comment]
Good point, this issue should be to handle this messaging in the best way possible. A good question for some of our UX folks when the time comes.

**Comment by awolfe76** [comment]
Closed in https://github.com/cfpb/hmda-platform-ui/pull/247
