### ISSUE TITLE
Server communication mechanisms

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#2]
Need to decide on MVP communication mechanisms for both the initial upload and for receiving events about data parsing and validation.

We're circling around a simple POST over HTTPS for the file and WebSockets over WSS for events from the server (server-side events and the Event Source API are completely unsupported by IE).

**Comment by awolfe76** [comment]
Due to browser limitations we're going to stick with long polling (for now) for the events about data parsing and validation.
