### ISSUE TITLE
Don't post to /latest for submissions

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#205]
We should always post files to `/<submissionID>`. And possibly `/submissions`.

See https://github.com/cfpb/hmda-platform/issues/535 for the discussion.

**Comment by hkeeler** [comment]
We've also discussed `POST`ing the file to `institutions/{institution_id}/filings/{period}/submissions/` directly, and having that action be what creates a new `submission_id`.  This flow makes more sense to me.  After all, what is a submission without the file?

This would obviously be a change to both frontend and backend.  This could be spun off to its own issue as well if this one is intended as a quick fix.

**Comment by awolfe76** [comment]
I do have that listed on [this issue](https://github.com/cfpb/hmda-platform-ui/issues/204) (integration tracking) and [this one](https://github.com/cfpb/hmda-platform/issues/537) (endpoint creation tracking). And it makes sense to me too.

Updated the comment above with it.
