### ISSUE TITLE
Prototype to show persistence

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#22]
Begin to prototype the workflow for:
- [x] initial screen
  - [x] including possible listing of institutions for the filer and the progress with each
  - [x] including 'request a new bank'
- [x] file submission (what happens)
- [x] file upload progress
- [x] file upload progress combined with results
- [x] file upload fails midway through
- [x] first response returned from server
- [x] first error returned from server
- [x] if error stops the rest of the process

**Comment by wpears** [comment]
Nice work on this, PR soon?
