### ISSUE TITLE
Add edit descriptions

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#235]
@lesgou do have descriptions for each edit type, syntactical, validity, quality, and macro?
Right now we just have placeholder content, "This is the <edit type> description."

**Comment by lesgou** [comment]
1. **Syntactical**: Edits that check whether the loan/application register is in the correct format and whether the data covers the correct filing year. The loan/application register cannot be filed until the filer corrects all syntactical edit errors and reuploads the updated loan/application register to the HMDA Platform.
2. **Validity**: Edits that check whether there are valid values in each data field. The loan/application register cannot be filed until the filer corrects all validity edit errors and reuploads the updated loan/application register to the HMDA Platform.
3. **Quality**: Edits that check whether entries in the individual data fields or combinations of data fields conform to expected values. The loan/application register cannot be filed until the filer either confirms the accuracy of all values flagged by quality edits in the HMDA Platform, or corrects the flagged values and reuploads the updated loan/application register to the HMDA Platform.
4. **Macro Quality**: Edits that check whether the submitted loan/application register as a
   whole conforms to expected values. The loan/application register cannot be filed until the filer either confirms the accuracy of all the values flagged by the macro quality edits in the HMDA Platform or corrects the flagged values and reuploads the updated loan/application register to the
   HMDA Platform.
