### ISSUE TITLE
Make IRS and Signature all one checkbox

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#286]
We can let the IRS be associated directly to the process of signing the submission.

#### In [`/components/IRSReport.jsx`](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/IRSReport.jsx)
- [x] remove the [checkbox](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/IRSReport.jsx#L71) from the IRS report
- [x] remove the [warning function](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/IRSReport.jsx#L11) and its [call](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/IRSReport.jsx#L69)
- [x] remove the [confirmation function](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/IRSReport.jsx#L3) and its [call](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/IRSReport.jsx#L84)
- [x] clean up [props](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/IRSReport.jsx#L94), remove `receipt`, `timestamp`, ~~`status`~~, `onIRSClick`
- [x] ~~clean up [defaultProps](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/IRSReport.jsx#L99), remove `status`~~

#### In [`/containers/IRSReport.jsx`](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/containers/IRSReport.jsx)
- [x] clean up [mapStateToProps](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/containers/IRSReport.jsx#L20), remove everything except `msas` and `isFetching`
- [x] remove [`mapDispatchToProps`](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/containers/IRSReport.jsx#L51)

#### In [`/containers/Signature.jsx`](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/Signature.jsx)
- [x] update [warning message](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/Signature.jsx#L21)
- [x] update [label](https://github.com/cfpb/hmda-platform-ui/blob/63b8743f97c7173023aa62350ae1b7cad5cd7a04/src/js/components/Signature.jsx#L45) for checkbox

**Comment by lesgou** [comment]
Draft language for the signature: I am an authorized representative of my institution with knowledge of the data submitted and am certifying to the accuracy and completeness of the data submitted.
