### ISSUE TITLE
Quality verification

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#288]
Quality edits need only one verification for all edits.

- [ ] add a button with a message to say something like "i've verified my quality edits and am ready for the next step"
  - this button should take the filer to the next stage of the process, most likely macro edits, but if not macro edits exist it could be the signature/irs "page" (see #286)

**Comment by lesgou** [comment]
Recommended language for the message:
"I have verified the accuracy of all data fields referenced by quality edits."

**Comment by awolfe76** [comment]
Closed by #309
