### ISSUE TITLE
Implement basic file submission page

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#3]
Basic functionality is allowing the submission of a file and signaling to the user when it has been fully received by the server.

**Comment by awolfe76** [comment]
#14 has a possible component breakdown for this page.

**Comment by awolfe76** [comment]
#19 started basic framework for this.

**Comment by awolfe76** [comment]
@wpears - I think this is what you are currently working on, right? And #28 might complete this?

**Comment by wpears** [comment]
Yeah will be closed by #28

**Comment by awolfe76** [comment]
#28 is merged, closing.
