### ISSUE TITLE
On hold: Allow submissionId in the URL

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#302]
One use case for this is to allow filers to view previous submissions in the UI, something like `institutionId/filingPeriod/submissionId/...`.

We'll at least have to:
- [ ] update the routes in [`index.js`](https://github.com/cfpb/hmda-platform-ui/blob/e33f4fdbdd78c33951f203789b968654edc54932/src/js/index.js)
- [ ] update [`actions.js`](https://github.com/cfpb/hmda-platform-ui/blob/e33f4fdbdd78c33951f203789b968654edc54932/src/js/actions/index.js) with an action to fetch a submission by `id`, rather than only the latest submission

_There may be more to it once we start the work._

**Comment by awolfe76** [comment]
Not sure if we need this right now. We'll keep it open but I'll change the title to include "on hold".

**Comment by wpears** [comment]
This is also dependent on the backend returning a submission by id, ie at `/institutions/<institution>/filings/<filing>/submissions/<submission>`. Currently that endpoint only supports `POST`s and the only fetchable submission is at `.../submissions/latest`
