### ISSUE TITLE
Status transition on all quality and macro being verified

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#304]
Assuming the back-end will handle updating the submission status when all the quality and macro edits are verified, the front-end will need to be informed of this change.

The most efficient way would be in the response to the POST (either with a submissionUpdated flag, the submission code, or an entire submission object). Otherwise after every successful POST, the front-end will just need to query for the submission status (thus requiring no change to the current API).

**Comment by awolfe76** [comment]
This seems related to https://github.com/cfpb/hmda-platform/issues/849.

But we should probably also create an issue or 2 for the back-end to add the status to a few other endpoints.

**Comment by wpears** [comment]
Yeah, the front-end manages this transition manually at the moment, but as the back-end should be the source of truth for the status of the application, it makes sense to respond to a change in status there, rather than tracking it on the front-end (even if able). Moreover, this status is likely what the backend should be using guard against hitting the signature endpoint with an incomplete filing.

So perhaps an issue on the backend and close this one for now.

**Comment by awolfe76** [comment]
https://github.com/cfpb/hmda-platform/pull/930 will get us what we need.

**Comment by awolfe76** [comment]
@wpears - was there somewhere specific you were thinking about with "the front-end manages this transition manually at the moment"?

**Comment by wpears** [comment]
Was just commenting on how the code operated at the time.

This can be closed once https://github.com/cfpb/hmda-platform/issues/959 is done.

**Comment by wpears** [comment]
Closed with https://github.com/cfpb/hmda-platform/issues/959
