### ISSUE TITLE
Component for heading for FIs on the home page

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#31]
Create a component for the heading to display FIs and their progress (see #30).

Currently we have `Not started`, `In progress`, and `Complete`.
- Not started: the FI has _not_ submitted a file
- In progress: the FI has submitted, or resubmitted, a file and it's currently being validated or has been validated and is waiting on the next step
- Complete: signed

![fi-grouping](https://cloud.githubusercontent.com/assets/2932572/13464996/9f15adb0-e061-11e5-958e-18fc3fdbb251.png)

**Comment by awolfe76** [comment]
See #30 for possible API call and response the will help render the headings.

From that issue:
- `status` allows us to render the correct content and links
  - status codes could equal
    - 0 = hasn't started
    - 1 = running
    - 2 = done, with errors
    - 3 = done, no errors
    - 4 = signed

Assuming those status codes are what we use:
- 0 = `Not started`
- 1, 2, 3 = `In progress`
- 4 = `Complete`

**Comment by wpears** [comment]
Closed by #52
