### ISSUE TITLE
Timeout?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#317]
_This could require a change to the [auth](https://github.com/cfpb/hmda-platform-auth) repo too._

Once logged in, if you leave the app sit for a while (don't know how long) links will start to fail due to API calls failing. I think this is probably some sort of timeout issue.

But, we should either have the user logged back in or take them to the login screen.

**Comment by wpears** [comment]
This won't require changes to the auth repo, just a check here that credentials are fresh (if you refresh the page when the api calls are failing, you'll notice that you get redirected to the signin page). This seems like a bug in our silent renewal implementation here. I'll look into it.

**Comment by awolfe76** [comment]
I've had this happen a few times. I start seeing things like `https://192.168.99.100:4443/hmda/institutions/0/filings/2017/submissions/29/edits 401 (Unauthorized)`. A refresh doesn't take me to a login page, but it does make the API calls start working again.

**Comment by awolfe76** [comment]
@wpears - can we close this one?
