### ISSUE TITLE
Component to hold all FIs on the home page

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#32]
This component will act as a container for the FIs listed on the home page. It could contain 0 to n institutions (#30) , which will be grouped according to their filing status (#31).

![fi-all](https://cloud.githubusercontent.com/assets/2932572/13465218/a5bb199c-e062-11e5-8002-536d529c1f94.png)

**Comment by wpears** [comment]
Closed by #52
