### ISSUE TITLE
Placeholder for no institutions in current filing period

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#322]
We need a message ( No institutions required to file) rather than nothing

**Comment by lesgou** [comment]
@Kibrael and I briefly discussed and perhaps we should consider always allowing for existing users to file, regardless if the fi is not on panel for that filing year.  I'm not certain where this step currently is, but happy to discuss further.

**Comment by wpears** [comment]
Yeah, I think in this case it would be an issue for the backend (as we just consume their API response)

**Comment by awolfe76** [comment]
We _should never_ come across this but yes, we should have something here.

This should be partially handled during the registration process. During registration a user needs to select an institution (on panel or not) so we should always have at least one institution per user and the API would show that.

**Comment by awolfe76** [comment]
@wpears - does that mean we can close this too?

**Comment by wpears** [comment]
:fire: Patched into master :fire:
