### ISSUE TITLE
Error in package.json

### ISSUE THREAD

**Issue by Pavlo-Krysenko** [cfpb/hmda-platform-ui#329]
I have error in line 12:
"clean": "rimraf ./dist && mkdir -p ./dist ./dist/js ./dist/css ./dist/fonts ./dist/img",

Script run on Windows 10. According to (http://stackoverflow.com/questions/39727920/cant-use-mkdir-in-npm-script-from-windows) it is because command "mkdir" works weird in script on Windows.

Temporarily I install package mkdirp for npm and replace "mkdir" by "mkdirp" in your script.
Everything is working very well.

**Comment by awolfe76** [comment]
Thanks, @PavelKrysenko!

#330 should take care of the problem, along with a few other things that needed to be cleaned up.
