### ISSUE TITLE
Trigger resubmission from upload component after first submission

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#333]
Depends on #161 

In order to keep the upload component as part of the submission flow and breadcrumbs, we'll need to allow uploading a new file to trigger another submission (after warning with a resubmission alert).

This is a little nicer than requiring users to click a specific "refile" link from a different part of the app, since they've already learned where/how they upload a file and shouldn't be required to manually trigger the resubmission if they just manually navigate back to the upload screen and attempt to reupload.

**Comment by awolfe76** [comment]
@wpears - do we still need this one? I agree what you are saying seems cleaner. Does that also mean removing the refile button/modal? Or would the modal get triggered at a different point?

**Comment by wpears** [comment]
In my mind the modal is triggered by trying to trigger a drag/drop operation/clicking on the appropriate area. Seems like since that is the large obvious point of interaction on the page, it should be able to fit into the refiling flow (while still preventing accidental restarts with the modal).
