### ISSUE TITLE
Component to render progress for file submission and validation

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#34]
This component can be reused to show progress for:
- file upload
- file parse
- rows processed
- macro edit checks

We could use a progress bar along with some text.

Examples:
- upload could show `x of n MB` where `x` is climbing as the progress bar, well, progresses
- parse ... I think we need to know more here. Do we know the # of checks to parse? Is it row by row?
- rows processed could show `x of n rows`
- macro could show `x of 34 checked`

The component would need to know:
- an x value
- an n value
- a value type
- and the what (upload, parse, etc)

@wpears thoughts on reuse in these cases?

**Comment by wpears** [comment]
Sounds good to me. Though I think for parsing, we might not need a progress tracker, since it will likely happen almost simultaneously to the upload (parsing is faster than uploading, so by the time the user sends the last bytes over, the parse should be pretty much done). So sending over events for this would probably be info overload/confusing as it's all happening at once.

**Comment by wpears** [comment]
But yeah, a component that takes props of currentValue, total, and a what seems good. I'm a bit unclear on value type, as I think it should always be numeric.

**Comment by awolfe76** [comment]
For value type is was thinking about the difference is what we're counting. For upload its file size (so KB or MB, or even GB), for row by row its # of rows, and for macro its edit checks.

Although we probably don't need that, we can render those differently based on the what. So  to render something like `x of 30 MB uploaded` we'll know the `MB uploaded` because the `what` will be `upload`.

:+1: on the parsing tracker. We can ignore it for now at least and just notify them that it's ok.

**Comment by wpears** [comment]
Yeah, I think the what takes care of both in this case.

**Comment by wpears** [comment]
This has actually been appreciably solved by `Progress.jsx` for some time; closing ^^;
