### ISSUE TITLE
Component to hold submission and validation progress/results

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#36]
This component will act as a container for all progress and results during the file submission and validation process. It will consist of components for #34 and #35 (and likely a few others TBD).

![validation-full](https://cloud.githubusercontent.com/assets/2932572/13509980/6eebfd3c-e15c-11e5-8280-602c9ce1fc3a.png)

An API call to get the information required for this component and nested components might look like:

`/process?institution=[name]`

And might return a response of:

``` json
{
  "institution": "Bank 1",
  "status": 1,
  "rowsChecked": 33,
  "macroChecked": 0,
  "errors": {
    "syntactical": 2,
    "validity": 0,
    "quality": 1,
    "macro": 0
  }
}
```

The `institution` value if only to make sure its the correct FI.

Possible `status` values:
- 0 = uploading
- 1 = parsing
- 2 = row checks (syntax, validity, quality)
- 3 = macro
- 4 = checks complete
- 5 = signed

Using those values:
- if status is 0, we're showing the upload progress
- if status is 1, we're showing the parsing progress
- if status is 2, we're showing row by row and showing errors as the happen
- if status is 3, we render links (if needed) for syntactical, validity, and quality and we're showing the macro progress
- if status is 4, we remove the cancel button, show the link for macro errors (if needed) and show the download and view report links
- if status is 5, we're just allowing a review and possible resubmission

The `errors: {}` is how we update the counters.

The `rowsChecked` = rows processed for syntax, validity, and quality. The front-end should have the row count already to show the `out of n`.

We'll also know the total # of macro checks (can be a config value on front-end, or we can have it returned here) to show the `out of n`.

**Comment by jmarin** [comment]
@awolfe76 This is great. Do you know what the institution "name" is? I'm still struggling with identity management for this data set, especially considering how things will change in 2018

**Comment by awolfe76** [comment]
Great question @jmarin. I know you've brought that up a few times in other cases.

It has to be some unique identifier but I don't know what that is exactly. We need to figure it out. This is just one of many cases that won't work without it.

**Comment by wpears** [comment]
I'd say the process goes something like the following:
- All institutions and users have been created and stored internally as part of panel.
- When created, institutions are assigned a unique identifier
- Users have been appropriately authorized/associated with institutions
- When making a request to log in, users get back a list of all the institution IDs they are authorized to file for
- Andrew's endpoint is then hit with these IDs

So for the UI, we can probably assume there _will be_ unique institution identifiers and can proceed with API calls like the above.

**Comment by awolfe76** [comment]
#132 partially closed this.
This component still needs error counts and links.

**Comment by wpears** [comment]
#35 has error counts/links; closing this as `ValidationProgress.jsx` solves this broader issue as written
