### ISSUE TITLE
Content for "resubmission"

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform-ui#366]
Regarding the resubmission modal when a filer needs to reupload a file after reviewing the syntactical and validity edits: 

We should update the content to avoid confusion by users as this step will typically occur prior to submitting data. Whereas "resubmission" typically refers to providing data after it has been signed and submitted.
@keileyo

**Comment by awolfe76** [comment]
@lesgou - what should this say?

**Comment by lesgou** [comment]
Yes, please see #429
