### ISSUE TITLE
Application URLs and APIs

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#37]
In #30 and #36 we're beginning to discuss possible API calls and responses. Before going down that path too far, it seems worth it to start to layout the URLs that would be available on the front-end and some of the API calls necessary to render them.

This issue is meant to get the conversation started. We should tear this apart and build it back up if necessary.

_This issue doesn't show the possible json response from the api. It's probably better to define the response closer to the actual work._
##### URL
- `/` - the home page currently presents a list of institutions and the appropriate actions required to complete the filing (along with any other relevant filing content, help, faq, alerts, etc)
##### APIs
- `GET /institutions/[userEmail]` - returns a list of all institutions for that user
- `GET /filing-status/[institutionID]` - for each FI in the list returned in the call above, return the current filing status and history
  - _these 2 calls can be combined if its more efficient so that the first call returns filing status in the initial list (see [this comment](https://github.com/cfpb/hmda-platform-ui/issues/30#issuecomment-192263535) on #30 ... but the 2nd call is still needed for polling_
##### URL
- `/institution` - view/verify/edit the panel information
##### APIs
- `GET /instituion/[institutionID]` - get all panel information for the institution
- `POST /instituion/[institutionID]` - update the panel information
##### URL
- `/submit` - the file upload form
##### APIs
- `GET /filing-status/[institutionID]` - **for polling**, once a file has been submitted we can begin polling to render the filing progress
- `POST /submit/[institutionID]` - Post the file
- `POST /cancel/[institutionID]` - Cancels the filing process at any point
##### URL
- `/edits/[editType]` - renders the list of edits for all edits or for a specific edit type if provided; can also render justification areas for quality and macro if specificity and validity are successful
##### APIs
- `GET /filing-status/[institutionID]` - as a way to check if they should be allowed to view this page and to know if they can justify edits (specificity and validity are successful)
- `GET /edits/[institutionID]/[editType]`
- `POST /justification/[institutionID]/[errorID]` - allows us to store each justification (also required in persistence, a filer can justify one edit (without justifying all), leave and return and that justification should be persisted)
##### URL
- `/summary` - validation summary page, prior to signature
##### APIs
- `GET /summary/[institutionID]/[filingID]` - return summary data (data TBD)
  - `[filingID]` needed if we're going to allow filers to view past summaries
##### URL
- `/signature` - the signature page; only accessible if all edits are successful/justified
##### APIs
- `GET /filing-status/[institutionID]` - as a way to check if they should be allowed to view this page
- `POST /signature/[institutionID]`
##### URL
- `/confirmation` - confirmation page after signature
##### APIs
- `GET /filing-status/[institutionID]` - as a way to check if they should be allowed to view this page
- `GET /confirmation/[institutionID]` - high level summary data for the filing (data TBD)
##### URL
- `/reports` - combination of the IRS and MSA/MD reports
- `/reports/irs` - IRS report data
- `/reports/msa-md` - MSA/MD report data
- `/reports/edit-report` - edit history
##### APIs
- `GET /reports/[institutionID]/[filingID]/[reportType]` - report data, default to both IRS and MSA unless `reportType` is set
  - `[filingID]` needed if we're going to allow filers to view past summaries
#### Notes/Questions
- Do each of these URLs (not the APIs, they do need it), other than the home page, need a `/[institutionID]` or should we update a variable to track the institution? Specifically for the case when a filer has more than one institution. We can know the `instituionID` when they click. But, if we want more useful URLs (they can type it) it might be worth including ... will be difficult though unless the IDs are memorable.
- Most versions of the UI require the ability to poll for filing progress if all checks have not completed. This is handled by a React component and a `status`.
- The `GET /filing-status/[institutionID]` on nearly every page is there in case someone navigates to that URL by typing it in the browser. Our generated navigation should be smart enough to not display if it shouldn't be available.
  - Same applies to the `POST /cancel`, as long as the process is running filers should be able to cancel it.
- Some of the `GET` API could/should have the typical query strings, `sort` or `limit` or `filter`.

**Comment by schbetsy** [comment]
Are we assuming that any necessary data about the user (e.g. user id) is in headers?

**Comment by jmarin** [comment]
@awolfe76 regarding `POST /cancel/[institutionID] - Cancels the filing process at any point`  How would this work? The processing is asynchronous, so we can't stop it right away. At most we can send a message that will eventually interrupt the processing, but there might be a small lag. I guess I'd like to dive deeper into what needs canceling and when.

**Comment by awolfe76** [comment]
One idea behind the cancel was if the filer started to see a large number of errors appear, and they know they made an obvious mistake. Rather than have them wait for us to complete all edit checks we give them a way out, a cancel button. This button would send a request to the backend telling it to cancel processing the file for [this bank ID].

I don't think it has to be immediate except from the UI standpoint, which is easy enough. We can just show a "You've cancelled" message and stop the long polling for the progress. The backend progress can stop as soon as it can.

I would think we would also keep track of the fact that a filing was cancelled. It would be useful to show that in the UI at a later date (likely the "home" page where we list the institutions for the user).

This idea is only really useful to a filer with a fairly large number of rows. I would expect the process is very fast in most cases. So, maybe we would only show it in the case where `rows>x` (we'll have to wait to determine what x is) or if `time>x seconds` and `errors>n`. Just some ideas.

There was more conversation around this so @wpears and @debseidner may have more examples.

**Comment by jmarin** [comment]
@awolfe76 Thanks for the context, this gives me something to think about. I think what you described makes sense.

**Comment by awolfe76** [comment]
Closing. See https://github.com/cfpb/hmda-platform/issues/261 and #107 for more details.
