### ISSUE TITLE
Prototype for error tables and reports

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#39]
- [x] syntactical errors
- [x] validity errors
- [x] quality errors
- [x] macro errors
- [x] IRS report
- [x] MSA/MD report
- [x] Summary (signature page)

**Comment by awolfe76** [comment]
@debseidner @lesgou 

Does the MSA/MD report depend on 2 quality checks, Q029 and Q595? 
And just curious how that validation works in general?

**Comment by lesgou** [comment]
MSA/MD report is the Q029 macro edit.

It says, "based on the information you gave us for State, County, and Census Tract, we think the MSA/MD should be X. You reported NA."

**Comment by awolfe76** [comment]
So those checks are just quality checks but get their own reports. 

Q29 = MSA/MD is "NA" and we think there is a MSA/MD
Q595 = no branch in MSA/MD

**Comment by lesgou** [comment]
Q595 is more like:
You reported loans in these MSA/MD's where we don't think you have a branch. Please circle yes/no to confirm.

**Comment by debseidner** [comment]
Just to add to what Leslie said, we talked about the feedback we got from the Pilot testers on the Q595/IRS about how they want a way to inform us that they do or don't have a branch in that location any longer or have a new branch location. So we need to think that through too.

**Comment by awolfe76** [comment]
Round 1 of these is complete. Will be creating new issues soon and closing this soon.

**Comment by awolfe76** [comment]
Closing, see #42, #43, #44, #45, #46, #47, #48, #49, #50.
