### ISSUE TITLE
Recommended updates to ui - Macro Quality edits page

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform-ui#426]
- [x] Is it possible for quality and macro quality edits to have separate banners?
![image](https://cloud.githubusercontent.com/assets/9752096/23804054/992ca048-0586-11e7-8a21-2090504cb82c.png)

- [x] Recommend updating yellow banner for macro quality edits to be: 
You must verify the macro quality edits listed below and select the check box to confirm the accuracy of the data. If any of the data need to be corrected, please update your file and select the "Upload a new file" button. You will need to begin the filing process again.

- [x] Recommend adding some language to the description of macro quality edits: Macro quality edits check whether...
![image](https://cloud.githubusercontent.com/assets/9752096/23804492/154c3f98-0588-11e7-8b6f-1b235141b096.png)

Full language:
Macro quality edits check whether the submitted loan/application register as a whole conforms to expected values. The loan/application register cannot be submitted until the filer either confirms the accuracy of all the values flagged by the macro quality edits in the HMDA Platform or corrects the flagged values and reuploads the updated loan/application register to the HMDA Platform.

- [x] Recommend updating language for checkbox to: All data are accurate, no corrections required. I have verified the accuracy of all data fields referenced by the quality edits.

![image](https://cloud.githubusercontent.com/assets/9752096/23804274/575e3cf2-0587-11e7-8e74-0110a34db565.png)

- [x] Recommend updating language on second sentence once check box has been selected to: Macro quality edits have been verified.

![image](https://cloud.githubusercontent.com/assets/9752096/23804351/8c2d66e2-0587-11e7-9504-383e40fc09f0.png)

**Comment by awolfe76** [comment]
Partially done in https://github.com/cfpb/hmda-platform-ui/pull/434, but will wait for https://github.com/cfpb/hmda-platform/issues/849 do complete the rest.
