### ISSUE TITLE
Component to render quality edits

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#44]
While this component will act a lot like the one in #42 I think its different enough to justify being on its own.
### _With_ syntactical and validity errors

![quality](https://cloud.githubusercontent.com/assets/2932572/13790699/26390c7a-eac0-11e5-9abd-d57826f712dd.png)

The component renders the loan number and number of errors, as a link. This link expands to show more details about the error(s).

If syntactical and validity errors are still present, a informational message should appear to the filer.

The data required:
- loan number
- number of errors
- edit ID
- edit description
- field where the error occurred
- the incorrect value submitted
- whether or not the error has been verififed
### _Without_ syntactical and validity errors

Once the syntactical and validity edits have run without error, this component renders a bit differently. The informational message is removed and now a checkbox and verification message are rendered.

![quality-verify](https://cloud.githubusercontent.com/assets/2932572/13790848/b4251dbc-eac0-11e5-957f-f705c6484df4.png)

Now, the filer can verify all quality checks are correct by checking the checkbox next to the verification message. _(The only way to fix these errors is through a resubmission.)_ Checking this checkbox will cause **ALL** of the `Not verified` messages to say `Verified`.

![quality-verified](https://cloud.githubusercontent.com/assets/2932572/13791753/fb4cb08e-eac4-11e5-91f1-07a7de696611.png)

It will also make an API call to let the backend know this step is complete. This should be a persistence point.

**Comment by awolfe76** [comment]
Its possible that [`EditsSyntacticalValidity.jsx`](https://github.com/cfpb/hmda-platform-ui/blob/master/src/js/EditsSyntacticalValidity.jsx) can be tweaked to render this as well.

**Comment by wpears** [comment]
Closed by #88
