### ISSUE TITLE
Set OIDC-related URLs at container startup

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform-ui#451]
We have a few URLs used for OpenID Connect authentication that are set at build-time for the app.  These need to be switched to runtime attributes, preferably passed in to container startup via envvars.

These variables are set in [`packages.json`](https://github.com/cfpb/hmda-platform-ui/blob/master/package.json):
* `APP_URL`
* `HMDA_API`
* `KEYCLOAK_URL`

**Comment by awolfe76** [comment]
Closed by #455
