### ISSUE TITLE
Fix CSV for paginated endpoint

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#465]
The CSV endpoint was updated and now only includes an entire CSV download.

This means we can strip per edit csv download links, remove the perEdit csv fetch action and simply update the endpoint for `fetchCSV`

**Comment by awolfe76** [comment]
We should also think about how to keep the download link in view the whole time, like the submission navigation (see #471). We can keep in on the institution's page but we should make it available everywhere when edits exist.

**Comment by wpears** [comment]
Opened an issue for that [here](https://github.com/cfpb/hmda-platform-ui/issues/478)
