### ISSUE TITLE
Remove pagination buttons when there are <= 20 results

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform-ui#466]
When there's only one page of edits, we could remove the pagination buttons, so they aren't confusing.

<img width="1034" alt="screen shot 2017-04-07 at 2 46 11 pm" src="https://cloud.githubusercontent.com/assets/4295388/24815058/d6e9f7ba-1ba1-11e7-8df5-3cbfa07a6d79.png">

(_Are you still looking for UI feedback via GH issues? If not, let me know_ ✨  )

**Comment by wpears** [comment]
Yep issues are :stars:

I'll think about this one for sure. There needs to be a bit of an increase in visual separation between edit tables in general and in so doing that might ameliorate some of the confusion here.

I agree that it looks cluttered now / can be confusing about which pagination control matches with which table, but I have a bit of a soft spot for consistent navigation controls (so you have always get info looking to the nav area), but it's certainly not unheard of to drop pagination components when you have <=1 page of results (google does it, etc.)

**Comment by awolfe76** [comment]
Agree with everything above.

Removing the pagination until needed was on my list to create issues for, along with #467. 😄
