### ISSUE TITLE
Visual separation of edit tables

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#468]
To assist with #466 (or perhaps to address the root cause), edit tables should be visually separated more.

This could include any combination of:
 - `<hr/>`s
 - More whitespice
 - Larger headers
 - Alternating background colors (between white and `$lightest-gray`) for each `EditsTableEntry`

**Comment by awolfe76** [comment]
I've had a few thoughts about this.

- white space is a great idea, and maybe when combined with the others that you mention, or
- making them more "card" like ([example](https://dribbble.com/shots/1790652-Google-Material-exploration), base on [this](https://material.io/guidelines/components/cards.html)), so having the `$lightest-gray` as the background and the edits with a white bg


I think we can play and demo here a bit.
