### ISSUE TITLE
Funky Alignment in Navigation Bar

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform-ui#469]
4 of the 5 circles are below the line, 1 is on it. 
(Ignore the "Automatically logged out" message in the screenshot; the same alignment issue is true on all submission pages)

<img width="937" alt="screen shot 2017-04-07 at 3 31 04 pm" src="https://cloud.githubusercontent.com/assets/4295388/24819396/6fc1a734-1bb2-11e7-9a9a-5871ee2c4b04.png">

**Comment by awolfe76** [comment]
Interesting. What browser?

**Comment by schbetsy** [comment]
Chrome on my CFPB Mac.

**Comment by wpears** [comment]
Was this with your browser collapsed to 1/2 - 2/3 width?

**Comment by schbetsy** [comment]
I tried again so I could double check. It happens when the browser window is 948 px wide or less.

**Comment by awolfe76** [comment]
Thanks! I had created #473 with this kind of thing in mind. I'll reference this issue over there.

**Comment by awolfe76** [comment]
Looks like this is happening at 963px (and possibly changed due to some other PRs).
