### ISSUE TITLE
Upload page temporarily freezes after pressing "Upload"

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform-ui#470]
When I uploaded a large file (`clean_14117-lars.txt`), I saw about a 4 second lag between pressing the "upload" button and seeing the gray/green dots that show the status of "uploading", "parsing", "validating".

Not sure if it's avoidable, but I wanted to let you know.

**Comment by awolfe76** [comment]
We can definitely render that component sooner, nice catch.
