### ISSUE TITLE
Refile warnings

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#474]
These could use a little attention:

![warning-qual](https://cloud.githubusercontent.com/assets/2932572/24822732/805e5b2e-1bc5-11e7-904d-e55bfa882aec.png)
![warning-syn](https://cloud.githubusercontent.com/assets/2932572/24822731/805df71a-1bc5-11e7-9d7b-8b55441d346f.png)

The spacing seems off, the positioning of the refile button, some bold test on the syntactical and validity but not on the quality/macro.

Do we want to show the refile button so prominently on the quality/macro warning. We don't want to mislead the filer into thinking that's the only (or best) option for those edits.

**Comment by wpears** [comment]
If the "select the 'upload a new file' button" text is in the warning, we'll need the button in the warning as well. Agreed re: bolding and spacing between content and button.
