### ISSUE TITLE
Should we split syntactical and validity to their own pages?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#475]
IMO we should. It keeps it more consistent, each edit type with its own page. Even though the two are similar in that they require a refiling, I think the separation makes the experience cleaner overall.

**Comment by wpears** [comment]
I think the reason we grouped them onto the page still holds, namely, that it's useful to have all the things filers *have* to change on one page.

Also, I think the distinction between syntactical / validity edits is essentially artificial and so separating them into distinct pages could be more confusing.

**Comment by designlanguage** [comment]
I agree with @wpears. Steps should exist to help the user understand their place in the process. I'm not sure what the user gains by seeing syntactical and validity edits separately and adding a step. Because of pagination, having the content for both in a single step shouldn't be overwhelming.
