### ISSUE TITLE
Quality and macro warnings - best way to refile

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#486]
Should the quality and macro warning just provide a link to re-file instead of a button?

The warnings currently look like this:

![quality](https://cloud.githubusercontent.com/assets/2932572/24963580/fa0acb56-1f6c-11e7-9395-65e273830c4d.png)

In this case, the best/easiest option for the filer is to verify these edits, having the button seems to be a bit much (not the most important action to take) but it's necessary to provide the ability to easily re-file.

**Comment by lesgou** [comment]
Sounds good to me.  Maybe update the language to "....please update your file and Upload a new file." with the "Upload a new file" as the link?

**Comment by awolfe76** [comment]
Closed by #485.
