### ISSUE TITLE
Conversation about app flow

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#51]
During standup a few days ago the question was asked, "what happens when a filer clicks a 'begin filing' link on the home page?" I think for now a basic flow of just clearing the existing elements and showing the upload form is fine. There also needs to be a "Home" link to return to the list of institutions, maybe just above the heading "[name] filing on behalf of [institution] in [year]".

From the home page, nearly the same would apply if the filer wants to view the current progress of filing. Existing elements are cleared and the progress, as links where necessary, is shown. 

And again, from the home page, if the filer wants to view a portion of the report that is already complete, the existing elements should clear, the heading and progress (no matter the state) should appear on the left and the report selected on the right, syntactical for example.

From other pages, it's likely that links will only be swapping content on the right, the reports and confirmation content ... unless the "home" link is clicked. The "home" link would clear existing elements and display the list of institutions again.

We can always tweak this later, but I think thats a start.

@wpears

**Comment by wpears** [comment]
The left and right parts of the "view a part of the complete report" scheme is interesting. Originally I was envisioning something like Pilot with a static nav, see https://github.com/cfpb/hmda-platform-ui/issues/20.

So clicking into a report or the status of an institution from a home page would bring you somewhere into the flow from submit -> validate -> reports -> summary -> sign. That is, the page is cleared and just the linked to component, nav, and static stuff like homepage link are shown. The user could navigate freely backwards within that submission process (say they want to confirm the size of the file they uploaded). Any time they want to go back to the homepage they'd just click the top-left home button.

That said, the idea of having a wider view into the whole edit process _while you edit_ could be a good one... then again it would be somewhat odd for your first viewing... Keeping the home page open when there are no links or reports would probably be wasteful and distracting. I guess it really depends on the necessity of comparisons _between different attempted submissions_. My gut reaction is that while is _could_ be useful, those states are actually less common. Thoughts @awolfe76

**Comment by awolfe76** [comment]
I _think_ we're saying the same thing. 

I agree with this following paragraph completely.

> So clicking into a report or the status of an institution from a home page would bring you somewhere into the flow from submit -> validate -> reports -> summary -> sign. ...

 Basically the prototype moved that nav to the left hand side instead of as a heading. This was done so that the nav could also act as a presentation for progress as well, where the nav gets added and linked as the file gets processed. (And the left hand nav fits a known design pattern at CFPB.) Filers could still navigate freely to any point of the filing/validation process.

For this -

> Keeping the home page open when there are no links or reports would probably be wasteful and distracting

We had discussed the home page have more content, things like FAQs, other notices and alerts, links to other docs like the reg or specs, etc.

And I'm not completely sure what you mean by -

> I guess it really depends on the necessity of comparisons between different attempted submissions.

**Comment by wpears** [comment]
Ahh righto. We're in agreement then. When you were talking about the left and right I got a sudden vision of keeping the homepage component open while checking the progress of a submission. Which I think has some cool properties but was **not** what you were saying ;) We're on the same page here.

Conversation had; closing
