### ISSUE TITLE
IRS totals row

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#515]
The totals row of the IRS currently shows on all pages, when pagination is used.

![totals](https://cloud.githubusercontent.com/assets/2932572/25617221/3a36fe0a-2f0f-11e7-8c54-8271761ca6cf.png)

Is this ok? Should we only show the totals on the last page? Or should we split the totals row out into its own table and have it always be shown?

**Comment by lesgou** [comment]
I think we should only show the totals on the last page, which encourages filers to flip through all the pages and review the data on all the pages.

**Comment by designlanguage** [comment]
If the totals are relevant/helpful to see, I don't think they should be buried. They can be visible at all times, but separated from the paginated table so it's clear it isn't the total for each separate page.
