### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#527]
After moving to the sticky header, we've lost most of the progress indicating-goodness from before (currently we only have a 1px line, which is pretty unclear if you don't know what you're looking for since it's also right on the dividing line between the header and the content below).

We should do some work to reinvigorate the progress indicator, which may include:
 - broadening the width of the indicator to 3-4px
 - separating the bar into segments to align with navbar items
 - pinning the width of the indicator to the width of the nav bar (so it doesn't extend too far past the first and last item)
 - reintroducing overlaid numbers to each segment to further emphasis progress
 - others

Thoughts @awolfe76 @designlanguage

**Comment by awolfe76** [comment]
💯  I _think_ we all like the idea of progress and steps, but something felt a bit off with it still. I had a quick chat with @designlanguage the other day about some of this and I'm pretty sure it's one of many things on his todo list. 😜

**Comment by designlanguage** [comment]
With the sticky header, there are now two indications of progress. I'm not sure we need to align them as much as we need to make one execution convey the appropriate information. Is there anything the progress bar conveys that the navbar doesn't?

@wpears @awolfe76

**Comment by designlanguage** [comment]
(I'm assuming the check marks are still being used, but maybe they're gone now?)

**Comment by awolfe76** [comment]
The checkmarks are gone at the moment too but can be added back easily. Is there a preference for which to use, progress bar or checkmarks? I'm open to either, just would lean towards the one that will be the clearest to filers.

**Comment by designlanguage** [comment]
I'd like to discuss it a bit more. I think check marks are clearer because they're directly connected to the text, but I understand the vertical space saved with the progress bar.

**Comment by awolfe76** [comment]
Yeah, maybe that's what was throwing me off with the steps before ... that it was being combined with the progress bar. 

What if we remove that, at least for now, when we add back in the steps?

**Comment by designlanguage** [comment]
#569
