### ISSUE TITLE
Vertical spacing on fixed position headers

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#528]
I think the fixed position, sticky headers currently take up a bit too much vertical space, particularly when a warning exists (which will be the usual case throughout filing). This could be solved by removing the `UserHeading` from the nav bar when it is pinned to the top

Compare
<img width="1349" alt="screen shot 2017-05-09 at 11 44 11 am" src="https://cloud.githubusercontent.com/assets/1558033/25866993/230819b4-34ad-11e7-82f2-72cc9630f8f5.png">

with
<img width="1350" alt="screen shot 2017-05-09 at 11 49 09 am" src="https://cloud.githubusercontent.com/assets/1558033/25867150/920f8734-34ad-11e7-94a1-5d00d2f87908.png">

@awolfe76 @designlanguage

**Comment by designlanguage** [comment]
I agree that we should condense that space and I like this solution. I'm not sure how important the `UserHeading` when someone is lower in the page. If most people are filing for a single institution, maybe not very.

If it needs to remain visible, it could live to the left of the nav bar (though differentiated visually to avoid confusion).

**Comment by awolfe76** [comment]
I agree. 

I think we can remove the user heading from this part. At one point we had the filer name there as well and decided it would be ok to leave it only in the main header ... they'll know who they are. I think this same thinking can be applied here too. At this point, they will be aware of the institution and the year. Plus, it's still part of UI, just not sticky.
