### ISSUE TITLE
Make edit report CSV download always available

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#530]
We should have the edit report CSV download available from all submission pages. Possibly fixed along with the edit navigation.

**Comment by awolfe76** [comment]
#480 removed the current filing from the previous filings, but now there is no way to download the edit report for the current filing. The previous filings list was the only way.

**Comment by keileyo** [comment]
Re-opening this issue as initial user testing indicates that it is necessary to have the option to download the csv edit report from the syntactical & validity, quality and macro quality pages.

**Comment by designlanguage** [comment]
Since the actionable area on these pages is currently in the error message at the top of the page, the edit report should be made available in that banner.

On quality edits, this could be language added to the existing message. Maybe: "You can **download the edit report** for your reference." 

@keileyo @lesgou

**Comment by lesgou** [comment]
Just to confirm, @designlanguage do you mean for the edit report also to be available when the banner is green for the quality edit reports?

**Comment by designlanguage** [comment]
Yeah, I think that makes sense.

**Comment by designlanguage** [comment]
Here is how we might include the edit report on each page. @keileyo - could use your assistance with wording.

It appears in the banner at the top as a link. For parsing errors, it should probably have a different name so it's less confusing for users.

![screen shot 2017-08-16 at 12 24 05 pm](https://user-images.githubusercontent.com/10562544/29374249-b5aa9de0-827e-11e7-82ce-2e271f51feab.png)

And it doesn't persist at the top, it scrolls up only leaving the nav bar, but we add a button for the edit report under the main heading, along with a bit more text. In the case of parsing errors, again, maybe it's a bit different: "Review the errors below or download the report." And the button might read "Download the report of errors". For edit reports, the button could say "Download edit report".

![screen shot 2017-08-16 at 12 24 25 pm](https://user-images.githubusercontent.com/10562544/29374393-2fb2d530-827f-11e7-98e4-271ba95dba86.png)

At the end of the error list, the red banner could appear again at the bottom of the page before the resources.

**Comment by keileyo** [comment]
If I'm not mistaken, we don't offer a download of the parsing errors (though this could apply in the future if we add that functionality). 

I'll address the wordsmithing on the edits side once I can access the platform tomorrow :)

**Comment by awolfe76** [comment]
This is working now. I have link in the warning that downloads the current edit report. I just need the wording for each case, syntactical/validity, quality, and macro.

There isn't a download for the parsing errors so we're ok there.

**Comment by keileyo** [comment]
@awolfe76 I think we can stick closely with what @designlanguage proposes above. How about

For syntax/validity
## Your file has syntactical and/or validity edits.
Please review the edits below or download the edit report. 
Then update your file and select the "upload a new file" button. 

For quality/macro
## Your file has quality edits. 
Please review the edits below or download the edit report. 
You must verify the edits and select the check box to confirm the data is accurate. If the data need to be corrected, please update your file and upload a new file. 

For macro quality, the same as above except the header says "Your file has macro quality edits."

**Comment by designlanguage** [comment]
@keileyo - This looks good to me.
