### ISSUE TITLE
Possible errors

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#536]
Going to use this issue to track a list of possible errors within the application. We'll probably use this list to create new issues to better handle messaging these errors to filers.

**Comment by awolfe76** [comment]
This should be a good start.

All of the endpoints listed [here](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md#institutions-endpoints) can potentially return errors to the front-end. A few common errors are:

- `400: Bad request` - the request could not be understood by the server due to bad syntax
- `401: Unauthorized` - the request requires authentication
- `403: Forbidden` - the request was understood but will not be completed
- `404: Not found` - the request did not return anything, we are not likely to know why
- `405: Method not allowed` - the request is not allowed (we try to `POST` data when the endpoint only allows a `GET`)

A few common server errors that may be returned are:

- `500: Internal server error` - an unexpected error preventing the server from completing the request
- `503: Service unavailable` - server is unavailable to overload or maintenance

### Example

It's the filing deadline and everyone is submitting their HMDA data. Bank 0 logs in, goes to the upload page, selects their file and clicks "Upload". The front-end sees the response with a `503`, looking something like:

```json
{
  "code": 503,
  "error": "Service unavailable",
  "description": "Sorry, we're very busy at the moment. Please try again later."
}
```

In this case the front-end _could_ render the description below the upload form, maybe in place of the progress.

**Comment by awolfe76** [comment]
We may also have a few more that we use. I'll add them when I know.

**Comment by schbetsy** [comment]
As far as I can tell, your list above is complete, though I can add some details/clarifications.

 - Many `404` errors do come back with helpful error messages from the API. For instance, submission-related endpoints will use these messages: "Submission X not found for 2017 filing period", "2017 filing period not found for institution bank0", "Institution bank0 not found"

- `403`: Forbidden happens whenever a request doesn't meet the [authorization requirements](https://github.com/cfpb/hmda-platform/blob/master/Documents/API.md#authorization), _regardless of whether the url is legit_.

 - `400`: Here are the specific reasons why a request might get `400` status from the API:

|Path|Error Code|Error Reason|Error Message (from API)|
|----|----------|------------|------------------------|
|Upload|400|Submission indicated by URL is in any status other than "Created"|"Submission X not available for upload"|
|Upload|400|File extension isn't .txt or file can't be read|"Invalid File Format"|
|Signature|400|Submission is in any status other than "validated" or "validated with errors"|"Illegal State: Submission must be Validated or ValidatedWithErrors to sign"|
|Signature|400|json payload must have signed = true. This endpoint doesn't allow un-signing a submission|"Illegal Argument: signed = false"|


Let me know if you need more info.

**Comment by awolfe76** [comment]
Thanks @schbetsy.

@designlanguage @lesgou @keileyo - is this enough to get you started?

**Comment by lesgou** [comment]
:+1:  Thanks @awolfe76 and @schbetsy!

**Comment by awolfe76** [comment]
More details on when errors can happen ...

## Institutions landing page

- Here we make a call to load the institutions available to the user. 
- We also load details about each institution return from the above call, there can be more than one institution per user and in this case, there would be several API calls.
- Another possible call is to download an edit report CSV, either from the current or any previous submission.

## Submission pages

### Initial calls

- Here we start by making a call to get the latest submission for the institution.
- If the above call fails with a `404` (handled in this case) we make a call to create a new submission and if successful the upload would be allowed.
- We also make a call to get the chosen institution details, to show the institution name in the header.

### During upload

- We `POST` the file upload it to the back-end.
- If that is successful we start polling to get the status of the submission, this is used to render the upload/parsing/validation progress.
- If parsing fails, we make a call to get the parsing errors which are shown below the upload form.
- If the file successfully completes the upload/parsing/validation process we make a call to get the edits. This is used to create the messaging below the upload form and update the edits navigation.

### On edits pages

- When on an edits page we get all of the edits again (if we haven't done this already).
- Then we get the details for each specific edit. These are individual calls to each edit returned in the above call. For example, if S020 is found we would make a call for the details of that edit. This is done to allow for pagination of each edit.
- Quality and macro pages also allow for verification. This is a `POST` to the back-end that would say if the edits have been verified or not. This also returns a response.

### Summary page

- Here we make a call for the IRS report.
- And a call for the respondent and file summary information.
- And a call for the signature.
- There is also a `POST` for the signature which is used to update the status of the submission to signed. This also returns a response.
- Another possible call is to download the IRS report in CSV format.

---

I think that's it 😃 . We can definitely walk through this a bit more if we need to.

**Comment by lesgou** [comment]
Wow, this is super helpful. Thanks @awolfe76!

cc: @keileyo @designlanguage

**Comment by designlanguage** [comment]
@awolfe76 - This context definitely helps, but would it be possible (ie: not difficult) to add in which errors could be returned for each of the calls above? We're aiming to cover many instances of an error with a single message, but some might need to be tailored a bit.

**Comment by designlanguage** [comment]
@lesgou @keileyo - Using this as a place to brainstorm, here's a start for some of the messages. Let's chat about them.

### `401`
"Please **log in** to complete this request. If this problem persists, contact **HMDA help**."

_This message above just says what needs to be done to address the error. For the message below, it says what's wrong first, then what to do._

### `403`
"You must be logged in to access this page. Please **log in** and try again. If this problem persists, contact **HMDA help**."

### `404`
_It sounds like these errors already provide some context (thanks @schbetsy), but ideally these can be more actionable. Maybe it's just a sentence added at the end that's context appropriate, followed by, "If this problem persists, contact **HMDA help**."_

### `503`
"The HMDA platform is unavailable, either due to high traffic or regular maintenance. Please try **logging in** again later. If this problem persists, contact **HMDA help**."

**Comment by awolfe76** [comment]
~~@schbetsy is coming up with a list of the endpoints and errors messages that can be customized. But in the meantime, I think we're safe to assume all can be and come up with the messages. And based on what @schbetsy finds a few won't make it in.~~

**Comment by keileyo** [comment]
@designlanguage @awolfe76 perhaps tweak the generic 401 to read:

"An error occurred. Please **log in** to complete this request. If this problem persists, contact **HMDA Help**."

Agree that customization is ideal, but for a generic message, we should let them know that an error has occurred.

**Comment by awolfe76** [comment]
Updated https://github.com/cfpb/hmda-platform-ui/issues/536#issuecomment-313715790 because I think we're ok without that. Based on another conversation we're going to try to build these into the UI without requiring updates to the back-end.

@designlanguage all of those are possibilities, and since we'll do what we can on the front-end we can come up with the list and then if there are any issues with them we can work through them.

**Comment by keileyo** [comment]
Some outcomes from today's chat @designlanguage @awolfe76 

**400 errors** 

- Have a general error message directing the user to 1) refresh the page, 2) if the problem persists, logout & log back in and 3) if those fail & the problem persists, contact HMDA Help. 
- Specifically for 400 - Submission not available for upload:  Institute an automated fix with API calls to create the submission & upload the file
- Specifically for 400 - Invalid File Format:  On the tiny chance that this happens, render the same error message that the front end uses for invalid file formats 

**401 and 403 errors**
- For beta release, have a single error message similar to either that @designlanguage proposes above. The actions that we want the user to take are 1) to log in again 2) contact HMDA Help if the problem persists 

**404 errors**
- No customization for beta. Likely use the same error message as the generic 400 that directs users to 1) refresh 2) log in / log out 3) contact HMDA Help in that order 

**500 errors**
- Error message should instruct users to 1) log in again and 2) contact HMDA Help. 

**503** errors
- pursue "status page" solution documented by @wpears here [90](https://github.com/cfpb/hmda-explorer/issues/90)

**Comment by keileyo** [comment]
I think it makes sense to keep the "Sorry, an error has occurred." as the first sentence of each.  

![image](https://user-images.githubusercontent.com/13036571/28984890-1b750bec-792e-11e7-8d3f-f3dd5c068d25.png)

Suggestions:

**400 & 404**

"Sorry, an error has occurred. Please refresh the page and log into the application. if the problem persists, please contact HMDA Help."

**401, 403 and 500**

"Sorry, an error has occurred. Please log in to complete this request. If the problem persists, contact HMDA Help."

**503**
I believe the example picture in this file is the default 503 error. We can leave as is for beta while we pursue the status page solution mentioned above.
