### ISSUE TITLE
Update header title - row id

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform-ui#545]
Recommend updating header title "row id" to "Loan/Application Number"

**Comment by awolfe76** [comment]
@lesgou - if I'm remembering this correctly we had this at one point but changed it because "Loan/Application Number" didn't make sense when the edit was on the "Transmittal Sheet".

**Comment by lesgou** [comment]
@awolfe76 I think since that column displays either a Loan/Application Number or TS, that it makes sense to change the header. Filers will know where to update their TS info.
