### ISSUE TITLE
Make previous submissions expandable

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#568]
Allow the previous submissions to be expandable ... rendering a link which then displays the list.

**Comment by designlanguage** [comment]
I like the USDS guidelines for expandables. The exception is that I prefer including CFPB's "Show" and "Hide" next to the + or -.

![screen shot 2017-06-06 at 3 28 56 pm](https://user-images.githubusercontent.com/10562544/26848089-49e83646-4acd-11e7-8708-5d3dc3814c94.png)

**Comment by designlanguage** [comment]
Here's a bit more detail, and a few questions.

* If filers are versioning the files they upload, would it help to show the filename of the LAR file being validated?
* It would be very simple if the first step could turn into an expandable upon multiple uploads. If seeing the filename is a benefit, could the title of the expandable change after a new upload?
* The label of the +/- could be "Show previous"/"Hide previous"
* When open, the current "previous filings" language throws me a bit (maybe it wouldn't phase filers). I thought "View edit reports for your previous uploads" seems clear and matches the language at the top of the expandable.

| Closed | Open |
| --- | --- |
| ![screen shot 2017-06-07 at 5 01 51 pm](https://user-images.githubusercontent.com/10562544/26901627-8119148c-4ba4-11e7-8929-fc1888bf4a40.png) | ![screen shot 2017-06-07 at 5 02 05 pm](https://user-images.githubusercontent.com/10562544/26901628-811bd58c-4ba4-11e7-9eb3-49305b39bddb.png) |

**Comment by lesgou** [comment]
- [ ] 1. I think it would be helpful to see the file name they uploaded.  

- [ ] 4. I have no strong opinion, we just have to make sure that we are using "filing" and "uploads" appropriately.  Filings = gone through the entire process and submitted. Uploads = Gone through some portion of the process and not submitted.

**Comment by designlanguage** [comment]
@lesgou, @keileyo -

Here's another attempt at the expandable. 

The previous uploads and submissions don't exactly correlate to "uploads", so I brought it back to the bottom. We can name the expandable "History for this filing".

Within the expandable, I removed the numbers in the list and just used the dates for ordering.

| Closed | Open |
| --- | --- |
| ![screen shot 2017-06-13 at 5 19 09 pm](https://user-images.githubusercontent.com/10562544/27105170-9ce1d8f4-505c-11e7-98ab-ff19f6a86161.png) | ![screen shot 2017-06-13 at 5 19 47 pm](https://user-images.githubusercontent.com/10562544/27105169-9ce15cb2-505c-11e7-8258-2cdc9df89f6d.png) |

**Comment by lesgou** [comment]
:1st_place_medal:

**Comment by awolfe76** [comment]
👍  - I like it at the bottom. It's more removed from the current workflow but still available.
