### ISSUE TITLE
Bring back the steps to the edits navigation

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#569]
We had these previously but they were removed (by me 😉 ) until we could get a better idea of how it should work.

## Early example (but we don't have to keep this style)

![edits-nav](https://cloud.githubusercontent.com/assets/2932572/26495356/483db080-41f1-11e7-92d3-f74fbffdff52.png)

**Comment by designlanguage** [comment]
So I tried out a few things.

Initially, I was hoping to have the steps double as headlines for the sections, which would look something like this:

![screen shot 2017-06-07 at 1 07 13 pm](https://user-images.githubusercontent.com/10562544/26892545-af560b3e-4b86-11e7-81b1-e60494e967f4.png)

Speaking with @lesgou, if there are many types of edits (even with pagination), the remaining steps would leave the page, and that's not ideal.

The other two options have already been explored, but there are a couple details:

* I'd like to keep color on active/actionable areas to deemphasize completed or future items. In the steps, that would mean completed ones could be black, and future ones could be gray.
* The line behind the steps don't need to extend before the first step and after the last step. They can just connect the steps. They also don't need to change color; the focus can remain on the circles.

It could look like this:

![screen shot 2017-06-07 at 12 46 27 pm](https://user-images.githubusercontent.com/10562544/26894868-a9f4cb24-4b8d-11e7-9c9c-0bd60cc63a5e.png)

So the two options would be a persistent vertical navigation, or a horizontal one. I'd guess that vertical space is at more of a premium (especially if there are lots of edits), but the IRS might be constrained horizontally. 

| A | B |
| --- | --- |
| ![screen shot 2017-06-07 at 1 07 01 pm](https://user-images.githubusercontent.com/10562544/26895341-4ca8c414-4b8f-11e7-87ec-a6a0de8ec334.png) | ![screen shot 2017-06-07 at 1 07 25 pm](https://user-images.githubusercontent.com/10562544/26895340-4ca5a3ec-4b8f-11e7-91c2-798c929186f6.png) | 
| This matches the steps on the institutions page that has been proposed. There's a bunch of unused space under the steps though. | There's a bit less wasted space, but if vertical space is at a premium, this might not be ideal. |

I'm interested to hear preferences/feedback on this.

**Comment by lesgou** [comment]
Would "B" be persistent as well? If I am going through the edits and am at the bottom of the page, would I still be able to see the steps?

**Comment by keileyo** [comment]
@lesgou I'm not @designlanguage, but yes, I think the idea is B would be persistent as well. I like that one.

**Comment by awolfe76** [comment]
Yep, I like "B" too. Just to be clear, in the examples we aren't showing the progress bar (filling from 0% to 100%) here, just the idea of steps 1-5?

_I like removing it here since we have a progress bar approach now to the upload/edit process._
