### ISSUE TITLE
Re-work footer

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#573]
Change the footer to add the resources there, removing them from the home page. See [this example](https://cloud.githubusercontent.com/assets/10562544/26258756/13cb8f50-3c94-11e7-9e87-97a5570e3f81.png).

**Comment by designlanguage** [comment]
@lesgou - Can we discuss wording for these resources?

**Comment by lesgou** [comment]
@designlanguage sure thing! do you have a particular format in mind and I can draft? Or we can chat.

**Comment by designlanguage** [comment]
@lesgou - Roughly, the format would be what @awolfe76 [posted above](https://cloud.githubusercontent.com/assets/10562544/26258756/13cb8f50-3c94-11e7-9e87-97a5570e3f81.png), but we can chat. I'm hoping that the wording for the links can clear enough so we don't need descriptions or headings for each. Not sure if we can get there, but that's my goal.

**Comment by lesgou** [comment]
How about:
## Resources
[FFIEC HMDA Website](https://www.ffiec.gov/hmda/default.htm)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Resources for HMDA Filers](https://www.consumerfinance.gov/data-research/hmda/for-filers)
[HMDA Final Rule](https://www.federalregister.gov/documents/2015/10/28/2015-26607/home-mortgage-disclosure-regulation-c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**HMDA Platform Tools**
[Regulatory Implementation Resources](https://www.consumerfinance.gov/policy-compliance/guidance/implementation-guidance/hmda-implementation/)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- [File Format Verification Tool](https://cfpb.github.io/hmda-platform-tools/file-format-verification/)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Check Digit Generator
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Rate Spread Calculator

**Comment by designlanguage** [comment]
@lesgou - I like this... What if we move the heading from inside the second column though? Also, should we have hmdahelp@cfpb.gov in the footer (possibly as "contact us")?

| Resources | HMDA Platform tools |
| --- | --- |
| [FFIEC HMDA Website](https://www.ffiec.gov/hmda/default.htm) | [File Format Verification Tool](https://cfpb.github.io/hmda-platform-tools/file-format-verification/) |
| [HMDA Final Rule](https://www.federalregister.gov/documents/2015/10/28/2015-26607/home-mortgage-disclosure-regulation-c) | Check Digit Generator |
| [Regulatory Implementation Resources](https://www.consumerfinance.gov/policy-compliance/guidance/implementation-guidance/hmda-implementation/) | Rate Spread Calculator |
| [Resources for HMDA Filers](https://www.consumerfinance.gov/data-research/hmda/for-filers) | |
| [Contact us](hmdahelp@cfpb.gov) | |

**Comment by lesgou** [comment]
Makes sense to me!
