### ISSUE TITLE
Weird png logo issue

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#578]
Starting getting the logo with its lower half clipped when served through the app (though when opening the file directly it seems fine). P weird.
<img width="386" alt="screen shot 2017-05-26 at 2 22 03 pm" src="https://cloud.githubusercontent.com/assets/1558033/26513175/e05a35aa-421e-11e7-9fee-2916a7841bea.png">

**Comment by wpears** [comment]
❗️ autofixed heisenbug ❗️ 

(actually it was probably some sort of alignment/overlap issue, at least that's what I'll tell myself)

**Comment by awolfe76** [comment]
Sorry, forgot to mention that I saw this initially but a re-build seemed to have fixed it.
