### ISSUE TITLE
Back button/Redirecting

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform-ui#583]
I am logged in on the platform and am on the upload page. Before I upload a file, I hit the back button, and am stuck in a loop on a "Redirecting......" page:

![image](https://cloud.githubusercontent.com/assets/9752096/26649614/6ff041c0-45fb-11e7-832a-092e1358aee2.png)

**Comment by wpears** [comment]
Fixed by https://github.com/cfpb/hmda-platform-ui/pull/555

**Comment by lesgou** [comment]
:+1:
