### ISSUE TITLE
Add constant for filing period(s)

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#589]
Use a constant for the filing period. We could do this as an array, that was we account for future periods. Something like `export const FILING_PERIODS = ['2017']` and then in the future `['2017', '2018', ... ]`

**Comment by wpears** [comment]
More than just adding constants, this should probably be done either at container startup or Docker build time by injecting an envvar.

Thus, one could deploy any year this no code changes, just an argument to the build/deploy script.
