### ISSUE TITLE
Question regarding progress buttons/bullets

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-platform-ui#591]
Once the Upload, File Format Analyst, and Edit Verification steps are complete, should the red button/bullet next to Edit Verification complete be green? In this situation, I uploaded a clean file, with no syntactical and validity edits.

![image](https://user-images.githubusercontent.com/9752096/26843534-71cedcaa-4aa5-11e7-98e6-b538ca3f51eb.png)

![image](https://user-images.githubusercontent.com/9752096/26843686-ef6ae7ee-4aa5-11e7-8c9c-428619c8f264.png)

**Comment by designlanguage** [comment]
@lesgou -

That's is a good question and it has me thinking about each of these upload steps. At this part of the process, it seems all a user needs to know is that their file has been uploaded in the right format. That last notification seems a bit redundant with the rest of the steps we want them to walk through (or skip past). I'm not sure that last notification helps the user.

I'm also wondering if a user needs to differentiate between the progress of the file being uploaded and the file format analysis. There's nothing for the user to do after upload and before analysis, so I'm in favor of collapsing it into one item.

Ideally, this can be a holistic progress indicator of the entire file upload process:

![angularjs-directive-for-circular-progress-meters](https://user-images.githubusercontent.com/10562544/26847414-fbe59940-4aca-11e7-983b-07ee1264c2bf.jpg)

**Comment by designlanguage** [comment]
Here's how that could play out:

| Image | Note |
| --- | --- |
| ![screen shot 2017-06-07 at 1 12 33 pm](https://user-images.githubusercontent.com/10562544/26891753-1aca8410-4b84-11e7-9936-4db9e8a2bca3.png) | Actionable text should be prominent in the box. The user doesn't need to see "Review edits" before the file is uploaded. |
| ![screen shot 2017-06-07 at 1 12 39 pm](https://user-images.githubusercontent.com/10562544/26891755-1ad51772-4b84-11e7-8a0e-f9069159b148.png) | Once the file is selected, the actionable text in the box can be less prominent (but "Upload" would be activated). |
| ![screen shot 2017-06-07 at 1 13 56 pm](https://user-images.githubusercontent.com/10562544/26891757-1ad93028-4b84-11e7-85f8-273cf047ca1f.png) | Clicking upload could bring up a progress indicator. |
| ![screen shot 2017-06-07 at 1 14 18 pm](https://user-images.githubusercontent.com/10562544/26891756-1ad8e208-4b84-11e7-883b-b43ccefb34bc.png) | Whatever the error, (file type, document formatting, etc...) it would appear where the user is already looking. It doesn't seem that knowing whether the error occurred while uploading or parsing matters to the user. |

**Comment by wpears** [comment]
Closed by #597
