### ISSUE TITLE
Context for invalid password in registration

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#592]
If the password you enter doesn't follow one of the requirements, a box with all requirements pops up.

![screen shot 2017-06-06 at 9 26 59 am](https://user-images.githubusercontent.com/10562544/26844213-b26bef44-4ac0-11e7-90ed-537d5b60a851.png)

The USDS guidelines call for more context here if the password meets some of the requirements. I like this, but I think the text could be more connected to the checkmarks here, either in proximity or color to make the exceptions clear.

![screen shot 2017-06-06 at 2 02 27 pm](https://user-images.githubusercontent.com/10562544/26844337-0f50e4b2-4ac1-11e7-9707-23543af21be2.png)

**Comment by awolfe76** [comment]
@designlanguage - this issue should be created in the [-auth repo](https://github.com/cfpb/hmda-platform-auth/issues). I'll close it here.
