### ISSUE TITLE
Pagination Animation

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#595]
Currently, paging is quite jarring, both due to the instant scroll and the instant paging switch.

A clever fade / quick slide to top would allow this to be much nicer

**Comment by awolfe76** [comment]
Modifying the padding on the tables helps here as well by allowing the entire 20 rows to fit on the screen. It's currently set to `1.5rem` (by USWDS) but we could override that. Setting it to `.5rem` allows all rows to be on the screen (at given heights) along with the pagination.

_(Not saying it has to be `.5rem` just giving an example.)_

**Comment by wpears** [comment]
Yeah, I think less padding here is better (I had it set to 1rem in my testing). I also think the scrollTo is a crutch to fix the jumping problem specifically when moving to/from the last page (which will be incidentally solved by a scrollTo which will prevent a scroll jump). The padding fix won't address this last jump, but it definitely helps parsing the table visually, imo.
