### ISSUE TITLE
Comparison with Pilot

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#6]
We need to decide what to keep/port from pilot.

Need to talk to @debseidner about usability reports and design this UI to address any issues encountered with pilot.

**Comment by awolfe76** [comment]
We should add @benguhin to this conversation.

**Comment by awolfe76** [comment]
Closing. Several other issues created based on pilot feedback.
#15, #16, #17, #18

Another thing that came up in pilot was the need for better instructions. Issue(s) can be created later as we better define the submission workflow.
