### ISSUE TITLE
Reorganize CSS for components

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#60]
For maintenance reasons, I think it would be good to have one CSS file per component (it would be very easy to know where to make style changes and would also make the components somewhat more reusable. This would require reorganizing the src directory to instead of of having a folder for less files and a folder for js files, there would be a collection of folders for each component.

Alternatively, component css/less files could just be added to the current less directory separate from app.less. Thoughts, @awolfe76 ?

**Comment by awolfe76** [comment]
I'm all for giving the alternate a shot, where we would see something like `divisionHeader.less` in the `less` directory (if it was necessary). A problem that we may run into with that method is in reuse of styles. If `divisionHeader.less` and then say `editHeader.less` ended up containing the same styles we start to defeat the purpose of CSS. 

Guess we can just try to watch out for that kind of thing starting to happen. This is also why I like the approach of "one class does one thing", like where I created the `margin-top-0` and others in `app.less`. You may end up with a lot of classes inside your HTML but you are very sure what they are doing.

**Comment by wpears** [comment]
Good point. I think as long as we are leaning on CF styles and explicitly requiring them as dependencies of components this would still be a good approach/we won't be duping styles everywhere. Gonna close this issue and head in this direction.. if it starts to feel wonky it won't be too much effort to `cat combined css1 css2 ... cssn` and remove any dups.

**Comment by awolfe76** [comment]
:+1:
