### ISSUE TITLE
Update edit headings

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#607]
For each edit type we have a heading like:

![syntactical-headings](https://user-images.githubusercontent.com/2932572/27233617-12d199a0-5288-11e7-8089-d859944cb3e1.png)

The problem is that it can be a bit confusing to see "3 Syntactical Edits" but when reviewing the edits you might see that there are 5 total edits, like:
- 3 S020 edits
- 1 S100 edit
- 1 S010 edit

Can we update the "3 Syntactical Edits" heading to be "3 types of Syntactical Edits" and/or include the total number of edits?

**Comment by lesgou** [comment]
"3 Types of Syntactical Edits" works.
