### ISSUE TITLE
Nav button on upload page

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#629]
We are currently showing the nav button when the upload page is initially loaded:

![upload](https://user-images.githubusercontent.com/2932572/27594201-305a4416-5b27-11e7-8e21-ae324c7a932e.png)

The _potential_ problem I see with this is when parser errors occur. In this case we see:

![parse-errors](https://user-images.githubusercontent.com/2932572/27594231-419378ec-5b27-11e7-91e2-6c6b6e5ea260.png)

When we didn't have the idea of steps in the edits navigation showing this button initially was more important. Now, in the case of parsing errors, it will never be enabled.

Would it be better to not show the button on the upload page initially and only render it when a file successfully parses (filer can move beyond the upload page)?

**Comment by designlanguage** [comment]
@awolfe76 - I think the Review edits button should not appear until that action is needed. I mentioned it in [this issue](https://github.com/cfpb/hmda-platform-ui/issues/591) a little while back.
