### ISSUE TITLE
Knowing who did what in a filing (multiple filers for a single institution)

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#645]
@hkeeler pointed out that it could be useful for a filer to see who did what in the submission process. I'm wondering if the only context we need for that is in the expandable history on the institutions page.

I also don't think we need to indicate if the user has done something, only if _someone else_ has.

That could look something like this:

![screen shot 2017-06-30 at 1 56 08 pm](https://user-images.githubusercontent.com/10562544/27748060-e77d23f4-5d9b-11e7-9afb-39f0aa04c40b.png)

**Comment by wpears** [comment]
This will have a strict backend dependency: currently the status message/code is all we get back for a given submission's status. If the API response includes this information, we'll gladly display it.

**Comment by hkeeler** [comment]
Here's the corresponding backend issue: https://github.com/cfpb/hmda-platform/issues/815
