### ISSUE TITLE
No filings placeholder

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#648]
It should never happen that an institution will have no associated filings, but just in case (and kinda as a self-check on the data loading system), institution a simple note in the institution page if no filings exist for a given institution.

**Comment by awolfe76** [comment]
@wpears - closing this one. Looks like [this](https://github.com/cfpb/hmda-platform-ui/blob/3e42f9f290ee21040bedc052165995b55260695c/src/js/components/Institutions.jsx#L207) takes care of it.

**Comment by awolfe76** [comment]
Reopening ... that doesn't seem to be doing the trick

![no-filings](https://user-images.githubusercontent.com/2932572/29460628-acac6a74-83f6-11e7-84df-924931cc2183.png)
