### ISSUE TITLE
API bug causes missing IRS table

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform-ui#650]
There's a bug in the API where the IRS endpoint sometimes returns an empty result (see sample response below). When this happens, the UI currently doesn't show any IRS table or give any hint that there should be something in that section. Maybe we should inform the user that there's been an error?

Here's one way I've seen this happen:

1. Start the application with docker-compose
2. Create an account and log in
3. Upload a file (I used `edits-M_1124-lars.txt`, but I've seen it happen with others)
4. Verify Macro errors, proceed to Summary/Submission page
5. See that the IRS table isn't there
6. Check the "Network" tab of the developer console. See that the call to the irs endpoint had this response:

```json
{"count":0,"total":0,"msas":[],"summary":{"homeImprovement":0,"multiFamily":0,"lars":0,"FSA":0,"FHA":0,"amount":0,"oneToFourFamily":0,"refinance":0,"MFD":0,"conv":0,"homePurchase":0,"VA":0},"_links":{"self":"?page=1","prev":"?page=1","last":"?page=0","next":"?page=0","first":"?page=1","href":"/institutions/6999999/filings/2017/submissions/1/irs{rel}"}}
```

In my observation, it seems to happen on the first file submitted after starting the app. Needs confirmation.

**Comment by awolfe76** [comment]
@designlanguage @keileyo 

This is working but would like some help on the language before doing the pull request. This is used when https://github.com/cfpb/hmda-platform/issues/1031 happens.

![irs-bug](https://user-images.githubusercontent.com/2932572/29419951-986a9152-833e-11e7-8071-caec10142b86.png)
