### ISSUE TITLE
Warning a filer about a timeout

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#651]
@hkeeler @awolfe76 @wpears 

When the platform times out on a filer, I don't think there's any indication that something has changed. They'll only realize this after they try and do something that you can only do when logged in. A filer doesn't need to know everything that's happening in the background, but logging them out is a pretty significant action that they should be aware of.

Can we do one of the following things:

* Show a message on the page notifying them of the timeout and prompting them to log in again
* Kick people to a different logged out page, letting them know their progress has been saved, etc.
* In advance of a timeout, show a message warning them that it's about to happen and they can click to have more time in their session.

Along with that, I have a few more questions:

* How long does a filer have before their session times out?
* What (if any) actions renew the time in their session?
* If you are uploading a large file, will you be timed out during upload? And if so, will a file continue being parsed/analyzed?

**Comment by keileyo** [comment]
Referencing [#105](https://github.com/cfpb/hmda-platform-auth/issues/105) which has the possible Keycloak messages for a timeout / session / page inactive.
