### ISSUE TITLE
Institution with no submissions

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#660]
The UI should have some messaging for when an institution first enters the application. In this case, the institution will have the filing created, but no submissions. It currently looks like:

![fi-no-submission](https://user-images.githubusercontent.com/2932572/28214119-07bb192e-6877-11e7-8dc8-a0291ff77443.png)

Other cases, after a submission has been triggered, look like (notice the status message):

![fi-with-submission](https://user-images.githubusercontent.com/2932572/28214169-27694c96-6877-11e7-9662-5388c70cfb37.png)

@designlanguage @lesgou @keileyo

**Comment by lesgou** [comment]
:+1: to me.
Did you want to add more language?

**Comment by awolfe76** [comment]
I think for that first case, yes. Something that tells them there are no submissions but they can begin one. Sort of like the other message that tells them the current submission status.

**Comment by lesgou** [comment]
How about:

Current filing status is not started. You may begin your filing process by selecting the "Begin Filing" button below.


I am trying to keep it consistent with the way the other messages are structured. Does the "not started" filing status conflict with anything?
