### ISSUE TITLE
Create Tracker or Progress component

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#67]
This is currently in [`makeSubmitForm.jsx`](https://github.com/cfpb/hmda-platform-ui/blob/master/src/js/makeSubmitForm.jsx#L54), `createClass` is used. We can break out this component and allow it to be used in a few more cases, basically where any `x of y has been checked`.

**Comment by wpears** [comment]
Also, when this is stripped out, turn makeUploadForm into a component rather than a factory, as discussed in #70

**Comment by awolfe76** [comment]
Closed by #71
