### ISSUE TITLE
Design better tables

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#673]
We can spruce up our table design a bit, but it will require thinking a bit about data types and what we want to show/not show.

Also, and I believe @awolfe76 has already suggested this, we can likely do away with some of the cell padding to the tables are less bloated.

Some ideas:
https://medium.com/mission-log/design-better-data-tables-430a30a00d8c

**Comment by wpears** [comment]
@designlanguage

**Comment by designlanguage** [comment]
Totally agree. I have a few thoughts on this and I'll make some recommendations on this in the near future.

**Comment by awolfe76** [comment]
Also https://uxdesign.cc/design-better-data-tables-4ecc99d23356.

And we should definitely keep in mind making the responsive version of the tables cleaner (IRS for sure).

**Comment by wpears** [comment]
Some work done in #708 on this
