### ISSUE TITLE
Invalidate state appropriately to prevent stale renders

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#680]
Particularly, when moving back to the institutions page after a status transition there is a moment before the status is fetched where stale data is presented. This should be prevented and a loading icon should be rendered immediately.

**Comment by wpears** [comment]
Note also that this occurs even when state isn't marked as fetching, meaning the entire check could be removed when state hasn't changed.

**Comment by awolfe76** [comment]
Could we also update the state based on other endpoints? All of the relevant endpoints return the status, could we `dispatch(updateStatus(json)` from [here](https://github.com/cfpb/hmda-platform-ui/blob/811d80f5b53f8dc74b7c75d97ff1eb695f7a345a/src/js/actions/fetchEdits.js#L19) and other places?

Then not make the call if we already have the institution status.

**Comment by awolfe76** [comment]
Closed by #687
