### ISSUE TITLE
Checkboxes are waiting on results to check/uncheck

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#682]
Makes the app feel sluggish. Instead, the check should be instant and a spinner should load as the backend thinks.

**Comment by awolfe76** [comment]
Some things to consider here ...

If the call fails we'd have to un-check the box, would that feel odd too? Messaging would help of course.

Right now we have 2 different ways that check boxes are being handled:
  1. for quality/macro the check box triggers the API call (this is what you are referring to here, I think)
  1. and the signature checkbox doesn't do anything, it relies on the button to make the API call.

Is this going to be at all confusing to filers, the 2 different ways of handling this similar interaction?

We have to use the button for the signature check box, _maybe_ it would be better if we applied this to the quality/macro too? That would take away the "sluggish".

I think having more user testing done here would give us a better idea.
