### ISSUE TITLE
Remove the inactive/gray "upload" button

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#695]
Several people have tried to click on this first. We should remove it to focus attention on the drag/drop box. Blue upload button should appear after file is selected.

**Comment by wpears** [comment]
Do we want the upload button at all then? We could just key off the drop action, it actually feels pretty fluid.

**Comment by designlanguage** [comment]
The one benefit of the blue upload button is that it gives the filer a chance to confirm that they'll be uploading the right file name.

If that's not important, I think it can be removed all together.

Thoughts @lesgou @keileyo ?

**Comment by lesgou** [comment]
:+1: let's remove it.
