### ISSUE TITLE
Gain back vertical space taken up by static error message

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#699]
The 5 steps at the top of the page are static, and so are the error messages that appear. That doesn't leave much room to see the edits, especially when a filer gets to a paginated table. I'll propose a few things to address this, but the quickest fix I can think of is to not keep the error static and let it scroll off the page to allow more room for content.

**Comment by wpears** [comment]
Yeah this actually antagonizes me quite a bit. https://github.com/cfpb/hmda-platform-ui/issues/700 helps the user know an action needs to be taken on the page, so maybe having quite access to the "upload a new file" link isn't so important, since they can just scroll up after reviewing everything

**Comment by designlanguage** [comment]
@wpears - Yeah, it's a trade off. If we keep the upload link at the top, along with a link to the edit report, I think the page content itself might become less relevant as filers get more familiar with the process.

On the other hand, we could encourage them to review all the content by moving the upload action to the bottom of the page (and they wouldn't need to scroll up). I'm leaning towards something like this because there were a couple instances that people didn't know to scroll to see all the errors on a page. But I wonder if that should happen for beta.

**Comment by awolfe76** [comment]
I really like what #700 is proposing! And I'm all for saving some space by removing the fixed warning.

> If we keep the upload link at the top, along with a link to the edit report, I think the page content itself might become less relevant as filers get more familiar with the process.

I think this is true. I think that the ability to re-file, especially in the case where it's really the only way to proceed, should be very easy to access.

Same for the download of the edit report. This is something many people seem to ask for (and did in pilot as well).

I would vote for making those options stand out as much as we can.

All of that sort of goes against

> On the other hand, we could encourage them to review all the content by moving the upload action to the bottom of the page (and they wouldn't need to scroll up).

Again, I think over time the download and easy access to re-file become more important than seeing it in the UI. The download is important to be able to filter and makes it easier for them to update their systems.

_There was even talk at one point when building pagination that we could stop at x number for an edit and only offer the download. Paginating through 100's or 1000's of S025 edits in the UI doesn't do much for them._

---

Would rethinking this a little more get us somewhere? Something like in #610. Tweaking the nav to be presented more like that _might_ get us the space to message even more in the nav, like include the re-file link. Also might be too cluttered then but just a thought.

**Comment by designlanguage** [comment]
@awolfe76 - The more content we squeeze into the nav bar, the more people will ignore it, just like the text wall in the institutions page. We should keep it as clear and simple as possible, so I prefer #700.

I also think we should have upload/download actions at the top *and* bottom of the page. The colored banner can be at the top to begin with, but it shouldn't persist as we scroll. They're aware of the error and the actions they can take when the page loads, and if they scroll, we should let them see the page content. I would repeat the upload button/download edit report action at the end of the content as well.

**Comment by awolfe76** [comment]
Sounds good to me. Like I said, definitely good with #700. I like it.

And I think we're on the same page. I didn't notice the proposal was to have those actions available at the top and bottom. I thought you were saying to move them to the bottom only.

Having the warning/errors not persist, 👍 .

Sound like we're at a point where some mock-ups would be a good thing. 😉

**Comment by designlanguage** [comment]
@awolfe76 @wpears @keileyo 

Here's what I'm proposing for the banner/vertical space. We add more context to the nav, as I mentioned in #700, and let the banner scroll up.

We can also add more context to the upload box in the case of parsing errors to reinforce the status (users were confused about the state of their upload because of the message in the box). It could read "The data in **name_of_file** has formatting errors."

Then the red banner could appear again at the end of the page before the resources.

![screen shot 2017-08-16 at 12 40 02 pm](https://user-images.githubusercontent.com/10562544/29374626-1774c900-8280-11e7-8b62-3188b2cfb31d.png)

![screen shot 2017-08-16 at 12 40 10 pm](https://user-images.githubusercontent.com/10562544/29374627-1777259c-8280-11e7-8796-350eb55dcb61.png)
