### ISSUE TITLE
Make "HMDA filing" link look more actionable

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#701]
Tests revealed that some people didn't realize they could click on "HMDA filing" to return to the home/institutions page.

For an attempted quick-fix, can we underline it and give it a rollover color?

We've also referred to this as the "HMDA Platform". Shouldn't we use that wording instead (@keileyo @lesgou)?

**Comment by lesgou** [comment]
:+1:

**Comment by keileyo** [comment]
+1000 to this

**Comment by awolfe76** [comment]
I'm interested to see if this helps people. Maybe bringing back a "Home" link would work even better?

**Comment by lesgou** [comment]
I think Home makes sense....based on feedback.

**Comment by keileyo** [comment]
Should we re-open this? I definitely vote for having a clear homepage link. @awolfe76 @wpears @designlanguage

**Comment by awolfe76** [comment]
We're good. https://github.com/cfpb/hmda-platform-ui/pull/707 did just that. 😉

**Comment by keileyo** [comment]
a right okay, i missed that.
