### ISSUE TITLE
Moving/removing the paragraphs on the institutions page

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#702]
This could be broken down into smaller issues, but I want to capture the overall thinking here.

Ideally, we can simplify this text. If we need to keep it for clearance reasons, at least it can be moved to different areas. Instructions should appear when and where they're needed, and not before. The result should be that there is no right column of text, and we can make the left column wider (though not full page width for line-length considerations).

### First paragraph
This description can move under the Institutions heading. Ideally, it can be shortened to: "This page provides a summary of institutions for which you are authorized to file HMDA data," and remove the second sentence.

### Second paragraph
I'd like to see this mostly removed. If it needs to live somewhere, seems like this might belong  under "Filing Period". The only piece that is new information is about saving progress. Hopefully this could be shortened to *"Your progress will be saved in the event that you leave the platform before completing the filing."*

### Third paragraph
This can be moved from the right column. It can appear inside an institution box only after a filing is completed. Until that point, this information isn't relevant. Ideally, this can be shortened to something like: *"If you need to upload a new HMDA file, the previously completed filing will not be overridden until all edits have been cleared and/or verified and the new HMDA file has been submitted."*

### Fourth Paragraph
This could also be moved into the institutions box under the blue button, but only when there's an expandable present. Ideally is can be shortened to: "The edit report for any previous submission can be downloaded in csv format below."

**Comment by designlanguage** [comment]
@keileyo @lesgou - Thoughts on this? Think we can delete/move some of this text?

**Comment by lesgou** [comment]
@designlanguage I like all the recommended changes. My only concern would be the text that are recommended to be moved inside the institution's box. Would that make it too cluttered?

Basically, we need a way to tell filers "you can save and come back later" and "you won't have an edit report if there aren't any quality or macro edits"

We can address the completion of resubmission questions in an FAQ. We could also address the edit report question in an FAQ.

**Comment by designlanguage** [comment]
@lesgou - I'll mock something up to check if it'll be cluttered.

**Comment by designlanguage** [comment]
I'll work to break some of this into multiple issues, but here's my proposal for cutting text:

### Remove "Institutions"
There's no need for two headings, and the institution is already shown in the gray box. It's also strange that it's plural when most users will only have one.

### Supporting text
Under the main heading, the supporting text can read: 
"This filing period is open. You may file HMDA data for your authorized institutions below.  
Your progress will be saved if you leave the platform before completing your filing."

### Gray box extended
Since there's no righthand text column, the single column can get wider to allow for longer text line-length.

### Filing status
Simplify this and devote a whole line to this. We can attempt to reword the statuses as users didn't understand this.

### Dropdown language
The label for the dropdown should be clearer. Users were having trouble with this.

### Add text after submission
Some text from the righthand column can appear in the institutions box after submission.

@keileyo, thoughts?

### Here are the Mock-ups:

![screen shot 2017-08-14 at 6 07 37 pm](https://user-images.githubusercontent.com/10562544/29294163-00ab72d8-811c-11e7-8946-3e3964d02816.png)
![screen shot 2017-08-14 at 6 07 44 pm](https://user-images.githubusercontent.com/10562544/29294164-00ae5c96-811c-11e7-9fd0-7df31971f531.png)
![screen shot 2017-08-14 at 6 07 52 pm](https://user-images.githubusercontent.com/10562544/29294165-00b104a0-811c-11e7-981b-7c94b6c2bf3b.png)

**Comment by lesgou** [comment]
Adding @awolfe76 for confirmation on updating the messages in the statuses.

Also @keileyo thoughts on "filing period is open"? Considering that this will be available before the actual filing period (jan - march)?

**Comment by awolfe76** [comment]
I'll start working on this soon and make the updates I can.

If it looks like it would be better to update the back-end response for a few of these I'll open an issue in that repo.

**Comment by keileyo** [comment]
@lesgou re: the filing period, perhaps it should say "This filing period opens on January 1st, 2018."  This brings up the issue (while it may be easy), if we add the language to the institutions page, then we will have to update it when the filing period is closed because FIs can still come to the platform and test their data without a filing season being open. 

So it may make more sense to specify that the 2017 filing season is open between 1/1/18 and 3/1/18, during which you can submit your data for 2017. Perhaps we would then add something "The platform will remain available outside of the filing season upload, test and validate HMDA data."
