### ISSUE TITLE
Add language to let filer know they can logout

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#724]
It would be nice during a long validation process to message to the filer that they can leave/logout and come back later. See #642 and #717 for more details.

**Comment by awolfe76** [comment]
@designlanguage - in earlier conversations we thought this might be helpful.

Do you think it still is? If so, can you or @keileyo come up with some content?

If not, we can go ahead and close this issue.

**Comment by designlanguage** [comment]
@awolfe76 - I definitely think that text would still be helpful. I'll give it some thought next.

**Comment by designlanguage** [comment]
@awolfe76 - 

Question about this: If someone leaves the platform while a very large file is being parsed, and returns before it's completed, what will the filer see?

Will it be an in-progress status bar, or will it look like nothing has been uploaded yet?

Aside from that, I don't think it needs to be too different from what you mentioned @awolfe76 . It could be:

"Your upload will complete automatically, so you may leave the platform and log back in later."

@keileyo thoughts?

**Comment by awolfe76** [comment]
That's right. We'll wait for the file to be uploaded (the whole file is received by the back-end), then we'll display the message. So, it would be shown __only__ during parsing and validation.

If the filer leaves and comes back during one of those processes they would see the same thing as if they hadn't left; progress bar, correct messaging, etc.
