### ISSUE TITLE
Filename exists on first filing

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#728]
After I rebuilt the local setup, registered an account, logged in, and clicked begin filing I saw this 

![filename](https://user-images.githubusercontent.com/2932572/29459645-9ec3a034-83f2-11e7-9f30-c3ff620378c9.png).

Notice the filename, but I hadn't done anything yet. This was the first time through.

**Comment by wpears** [comment]
Yeah, I'd noticed this, but hadn't addressed it because it only crops up when rebuilding (ie wiping submission data), which we'd never do in production. It's not a terrible fix though, so I'll patch it.
