### ISSUE TITLE
Add propTypes to components

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#73]
[React docs](https://facebook.github.io/react/docs/reusable-components.html#prop-validation)
[Example implementation](https://github.com/cfpb/hmda-platform-ui/blob/master/src/js/Progress.jsx#L4)

Components to update:
- [x] DivisionHeader
- [x] EditReports
- [x] InstitutionContainer
- [x] InstitutionStatus
- [x] Resubmit
- [x] UserHeading
- [x] UserSelect

**Comment by wpears** [comment]
Closed by #75
