### ISSUE TITLE
Open-ended feedback link in beta banner

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#744]
I know there's more involved in this issue than just UI, but I'm starting here to document it.

Ideally, we could collect open-ended feedback on the platform during the beta period. If the beta banner appears on every page, that might be the best place to have a link leading people to a form where filers can provide feedback.

We'd have to decide where the forms would be sent, but even if it just goes to HMDA help, explicitly asking for feedback will be a good opportunity to catch issues outside of user testing.

Thoughts, @keileyo @awolfe76 ?

**Comment by awolfe76** [comment]
I think this would be great! Would be a straight forward thing to add a link.

**Comment by keileyo** [comment]
Sorry for being so incredibly late on this. Totally agree that we should have the open ended feedback & we already have the okay from PRA. I will handle the other internal (DIG) approvals. 

I strongly think that we should not have HMDA Help be the intake method, primarily because then a case in SF will be created for each piece of feedback & filtered up to us through the tiering system. It is relatively easy to have a new inbox in Outlook created (with an approval or two). I am also happy to get that started. HMDABetaFeedback@cfpb.gov?

**Comment by keileyo** [comment]
We have DIG approval to implement this now. The email address will be HMDAFeedback@cfpb.gov. As part of our DIG approval we need to include the sentence (or something similar). 

"Do not include personal information, such as an account number, personal address, or Social Security number.

**Comment by keileyo** [comment]
Suggest that in the beta banner after "This is part of our work to improve the HMDA electronic reporting process for financial institutions." we add "Contact us at HMDAFeedback@cfpb.gov to provide feedback on your experience with the HMDA Platform. Please do not include personal information such as an account number, personal address or Social Security number."

@designlanguage @awolfe76 thoughts?

**Comment by designlanguage** [comment]
Right now the banner looks like a disclaimer. I suggest we make it more actionable to attempt to get more feedback. The heading could be more of a call to action while also informing about the site's status. Something like:

### Send feedback on this beta release
or
### Help us improve this beta release

The body text is also getting a little long. Can we shorten it to something like:

| |
| --- |
| The beta HMDA platform is a work in progress, introducing HMDA filers to the new submission process before the filing period. If you have feedback on your experience, please send it to HMDAFeedback@cfpb.gov (do not include personal information such as an account number, address, or Social Security number). | 

And I'm not sure we really need the more information link here. Can it be in the resources at the bottom of the page? If it has to be here, let's simplify it to "For more information, visit http://www.consumerfinance.gov/hmda"

Thoughts @keileyo @awolfe76 ?

**Comment by awolfe76** [comment]
👍  to all of it! I'll update it and let everyone have a quick look before submitting the PR.

**Comment by awolfe76** [comment]
What do you think about this?

![beta-banner](https://user-images.githubusercontent.com/2932572/30922914-890f1610-a378-11e7-85fa-d17f785e70b0.png)

**Comment by designlanguage** [comment]
That's great @awolfe76 ! We just need a space before the parens. I want @keileyo to weigh in before we move forward though.

**Comment by awolfe76** [comment]
> We just need a space before the parens.

Good catch, it's updated.

**Comment by keileyo** [comment]
looks much better! great idea @designlanguage. I'm good with it.
