### ISSUE TITLE
Tutorial / video on signed out homepage

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#753]
We need a quick and easy way to provide a high-level overview of the filing process and resources available (faqs, hmda help etc.)

This could either be a carousel or modal carousel with pictures and explanations or a an animated video with similar content.

Then we could have the `Get Started Filing` button followed by "or `View the tutorial`".

If it's a modal carousel, we could show it automatically on a user's first view (checking via localStorage). If it's a video, we could show a modal with a message like: "Welcome to the HMDA Platform! Looks like it's your first time here, check out this video for an overview of the filing process."

**Comment by awolfe76** [comment]
Seems like this could be a bit easier and just add some of the steps to this page, maybe a few links, etc.

We have plenty of space here to play around with. Not sure if a carousel or modal is necessary.

### Current home page
![home](https://user-images.githubusercontent.com/2932572/30166401-3dac871a-93b1-11e7-91f7-ea6eec57d881.png)

**Comment by awolfe76** [comment]
Think something like the right side of https://www.dropbox.com/guide/business. Each step has a "card" with some quick bits of what's going on.

**Comment by designlanguage** [comment]
I'm not against the idea of the video or a slideshow, but those are both things outside of the process. We found that many users went straight into the process.

I know there were some technical hurdles to showing steps in the institutions page, but that seems to be a great way to indicate the steps of the process in context. I'd like to talk about revisiting this idea (#570).

**Comment by awolfe76** [comment]
@designlanguage - can we close this one now? (And look into #570 more.)

**Comment by designlanguage** [comment]
@awolfe76 - I would like us to look into 570 further. And if there are compromises we need to make, I'd like to discuss how we can still make something meaningful that presents the steps.

I see a video here as a separate thing. It could act as a teaser and help set the tone, so it could be worth exploring. I just doubt it can do the heavy lifting of changing a filer's expectation about how many steps are involved.

**Comment by awolfe76** [comment]
Sounds good. I'm going to close this one and open an issue about a video because I think while we need to start the conversation that work will be done outside the HMDA team.
