### ISSUE TITLE
Branding / official gov site

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#754]
Some users wanted more than our banner (or maybe didn't notice it). We could add the [updated banner](https://www.usa.gov/) to have a bit more explanation here.

We're kinda in a bind due to the requirement of not having our logo in the top left (which is kinda the official hey-this-is-who-this-app-is-associated-with sign).

Ultimately, we can probably skate by here knowing that *usually* people will only be directed here from other more branded sites/entities.

**Comment by awolfe76** [comment]
We could add the FFIEC logo back the top left. That would be a quick step to add more branding there.

**Comment by designlanguage** [comment]
Agreed, @awolfe76. "HMDA Platform" can move to the right of the logo.
