### ISSUE TITLE
Crank up the signature message happiness even more

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#755]
https://github.com/cfpb/hmda-platform-ui/pull/747 previously updated the success message, but we need more voltage there to ensure the user knows they are done (and that they're getting an email saying as much as well, see https://github.com/cfpb/hmda-platform/issues/1126).

There should be a line after the header reading something like:
Congratulations, you've successfully completed your HMDA filing for `<filing period>`!

**Comment by keileyo** [comment]
I agree, I like the amped up "happiness"

**Comment by keileyo** [comment]
Think i may be late to this, but the wording that @wpears suggested looks good to me.
