### ISSUE TITLE
Note on confirmation page to review and sign

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#756]
Some people thought that they were done upon reached the confirmation page, a green-background `alert-success` box with something like:
```
Your filing is ready to be signed and submitted, please review your filing summary and sign your filing at the bottom of this page.

If you discover an error in the summary you will need to update your file and upload it again.
```

Some messaging can then be pulled out of the IRS component (which, incidentally, has a typo https://github.com/cfpb/hmda-platform-ui/blob/master/src/js/components/IRSReport.jsx#L154 Update a new file -> Upload a new file)

**Comment by awolfe76** [comment]
This could be an `alert-info`. The `success` being green might just reinforce the thought that they were done.
