### ISSUE TITLE
Note in modal on what happens to old file/submission

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#757]
Even just "Your current file will be discarded."

**Comment by designlanguage** [comment]
This would only apply to the modal for a file that hasn't been submitted, right? I don't mind it being added, though I think the new modal language (#675) already helps address the problem. "Replace your HMDA data" relates more to what happens to the file than "Restart the filing process".

**Comment by awolfe76** [comment]
@designlanguage @wpears Do we need anything here?

**Comment by designlanguage** [comment]
@wpears I think we're good with trying the language in #675. If there's still confusion about that new text, we can bring this back.

**Comment by awolfe76** [comment]
Closing. Thanks @designlanguage.
