### ISSUE TITLE
Multiple institutions selected by default in registration

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#759]
When I last saw multiple institutions pop up in registration, they had to be individually selected to be added. Since all the applicable institutions should be added at once, and not as-needed, I think all the checkboxes should be pre-selected (if they aren't already). Opt-out instead of opt-in.

**Comment by awolfe76** [comment]
Closing here, see https://github.com/cfpb/hmda-platform-auth/issues/159.
