### ISSUE TITLE
Language for email verify notification

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#778]
User tests revealed that people wanted to know how much time they had to complete registration by email verification. Here's a thought for how we can update that language:

![screen shot 2017-09-18 at 10 02 22 am](https://user-images.githubusercontent.com/10562544/30545798-ae044746-9c58-11e7-8826-104cd1826160.png)

Verify your email to activate your account. 

An email with a verification code has been sent to george@bank0.com. 
The code will expire in 10 minutes. If you would like a new code, or you haven’t received
the email, click here to send a new one.

Thoughts @awolfe76 @keileyo @wpears

**Comment by wpears** [comment]
Closing in favor of https://github.com/cfpb/hmda-platform-auth/issues/164
