### ISSUE TITLE
List overall number of edits 

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#781]
We saw several instances in user testing where the number of edits appeared confusing. 

This came up when a user didn't scroll because they thought 1 type of edit meant only one edit. It was also hard to distinguish the edit name with the number of instances.

If we set up a slightly different structure/hierarchy, we can try to address this. Here's what I'm proposing:

### Syntactical/Validity
We can have an overall H2 heading, a simplified lead paragraph description of both underneath. Then each syntactical and validity edit would have an H3 heading. Since Synt. and Valid. are grouped in this step, they can also be grouped in the description. I'm open to thoughts on this, but it doesn't seem there needs to be separate syntactical headings. Also, we can include the total number of edits in gray parens after each heading. 

The simplified description can be something like this: 
"Syntactical edits show if the loan/application register format is incorrect and if the data doesn’t cover the correct filing year. Validity edits show if there are invalid values in data fields. Your HMDA data cannot be submitted until syntactical and validity edits are corrected in your file."

| Syntactical & Validity |
| --- |
| ![screen shot 2017-09-18 at 4 00 21 pm](https://user-images.githubusercontent.com/10562544/30561867-88d6d2fe-9c8a-11e7-903f-cbc258c29352.png) |

### Quality
These could be treated similarly. And the simplified description could be:
"Quality edits show if data fields do not conform to expected values. Your HMDA file cannot be submitted until the data has been verified or your file has been corrected."

| Quality |
| --- |
| ![screen shot 2017-09-18 at 3 58 53 pm](https://user-images.githubusercontent.com/10562544/30561810-506c22e8-9c8a-11e7-9264-6c37fa37437e.png) |

**Comment by awolfe76** [comment]
@designlanguage - for quality edits your example still says "4 types of Quality Edits ...", should we also remove the "n types of" part of that, to match the syntactical and validity update?

**Comment by designlanguage** [comment]
@awolfe76 - Yeah, I like that. Let's remove "n types of".
