### ISSUE TITLE
Upload a new file link broken with multiple institutions

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#783]
When a filer has multiple institutions listed _sometimes(?)_ the 'upload a new file' link will sometimes create a new submission for the wrong institution.

A possible fix to this is to reset the `institution` when the `/institution` route is taken ... so having a `clearInstitution` action distpatched [around here](https://github.com/cfpb/hmda-platform-ui/blob/8dc6bd9d9660f0aab863bfcbea1900a43ba7f654/src/js/containers/Institutions.jsx#L12) could do the trick.

It's safe to use the `state.app.institution` on other routes because the institution will be correctly set. This is __not__ the case on the `/institutions` route.

**Comment by wpears** [comment]
This sounds like a regression from https://github.com/cfpb/hmda-platform-ui/pull/745, but perhaps not.

Also, we aren't using the `institution` in the container, we're using `institutions`, so I don't think your theory on the refresh is necessarily correct.

**Comment by wpears** [comment]
Looks like the source of the bug is https://github.com/cfpb/hmda-platform-ui/blob/master/src/js/containers/ConfirmationModal.jsx#L23.

Still don't think clearing the institution would work here, you'll likely need to pass the id down into the button component which updates the institution on click.

**Comment by awolfe76** [comment]
> This sounds like a regression from #745, but perhaps not.

Yeah, definitely noticed this before then.

> Also, we aren't using the institution in the container ...

:) I meant `institutions`.

> Looks like the source of the bug is https://github.com/cfpb/hmda-platform-ui/blob/master/src/js/containers/ConfirmationModal.jsx#L23.

Yep, that's exactly the problem. I think your idea of updating on the button will work.
