### ISSUE TITLE
Upgrade Yarn

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#787]
### This will require a CR.

When we have a chance we should [upgrade our Yarn version](https://github.com/cfpb/hmda-platform-ui/blob/76e429efbfce9d3fba5b42e35e670b87fad09c9b/Dockerfile#L10). They have released [1.0.0 and beyond](https://github.com/yarnpkg/yarn/releases) with performance gains.

**Comment by wpears** [comment]
Along with #798, I think we actually want to remove yarn from the docker build process all together and just make sure the local dependencies of node and yarn are documented. We don't actually take advantage of the SKIP_JS_BUILD flag in compose and always build the front-end locally when testing.
