### ISSUE TITLE
Check `null` returns

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#802]
Check for places where we return `null` in components and see if we can do a better job of returning _something_, even if it's an error/warning.

See [here](https://github.com/cfpb/hmda-platform-ui/blob/f93f490133c30c6031ef2d962b032eb4d0521fe1/src/js/components/IRSReport.jsx#L142) in the IRS as an example.

**Comment by wpears** [comment]
A lot of times this is so we don't flash default content on an initial render. I'd say you might want to check the isFetching or fetched flags if they are available (we'd definitely want to display something informative if has has been `fetched` and we still have `null` data.
