### ISSUE TITLE
Add content for beta

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#810]
We need to add content to a few places within the application to let users know this is a beta release.

- [x] home page
- [x] create an account (this will be a PR to the auth repo)
- [x] institutions listing page
- [x] upload
- [x] signature (either prior to signing, on the receipt, or both)

@keileyo @designlanguage - you can add the content for each of these to this issue.

**Comment by designlanguage** [comment]
### Home page
The heading on this page isn't really accurate during beta, so I think the whole message can be adjusted:

__Get familiar with filing your HMDA data__
During this beta period, you may explore the new HMDA platform. It will be used to upload your financial institution's loan/application registers, review edits, certify the data, and submit the data for the filing year. All test data uploaded and accounts created during the beta period will be removed from the system when the filing period opens in January 2017.

### Create an account
* The heading can change to "Create a test account"
* There can also be an alert box under _go back to login_ and above _First name_ that says: "Any test account created during the beta period will be removed from the system when the filing period opens in January 2017."

### Institutions page
In the alert box add a sentence at the end:

"All test data uploaded during the beta period will be removed from the system when the filing period opens in January 2017."

### Upload page
Above the drag-and-drop box, add an alert box:

"All test data uploaded during the beta period will be removed from the system when the filing period opens in January 2017."

### Signature
* The text under "Signature" can say "To complete your test submission, select the checkbox below. Next, select the "Submit HMDA test data" button to practice submitting data. When the filing period opens, selecting the checkbox will certify the accuracy and completeness of the data submitted. 
* Add an alert box that says: "All test data uploaded during the beta period will be removed from the system when the filing period opens in January 2017" __(this might be redundant given the other messages on this page)__.
* Checkbox text can say "I understand this data being submitted is solely for testing purposes and will be removed from the system when the filing period begins in January 2017."
* Change button text to "Submit HMDA test data"
* In the green confirmation box, change the heading to: __HMDA test filing completed__
* Chance the first line in the green box to "Congratulations, you have successfully completed your HMDA test filing!"
* If a confirmation email won't be sent, that line should be removed from the green confirmation box.

Thoughts @keileyo and @awolfe76 ?

**Comment by keileyo** [comment]
Thanks so much for all of this content, @designlanguage. looks great. I have a few suggestions:

1.  I made a minor update to the final sentence to sneak in that the platform will be available for data collected in 2017. 

During the beta period, you may explore the new HMDA platform. It will be used to upload your financial institution's loan/application registers, review edits, certify the data, and submit the data for the filing year. All test data uploaded and accounts created during the beta period will be removed from the system when the filing period for HMDA data collected in 2017 opens on January 1st, 2018. 

2. Update "January 2017" to "January 1st, 2018" in all of the suggestions. 

3. I think that the checkbox in the signature stage is enough, likely can do without another alert telling them that the data will be removed prior to the filing period. 

4. Make sure that in accordance with #819, the submission confirmation box header would be "HMDA test filing accepted"

5. Like using alert boxes on upload & institutions page to avoid changing too much of the content during the meat of the process.

**Comment by designlanguage** [comment]
@keileyo - All these comments are great, thanks! 

@awolfe76 - Here's the revised content:

### Home page

__Get familiar with filing your HMDA data__
During this beta period, you may explore the new HMDA platform. It will be used to upload your financial institution's loan/application registers, review edits, certify the data, and submit the data for the filing year. All test data uploaded and accounts created during the beta period will be removed from the system when the filing period for HMDA data collected in 2017 opens on January 1st, 2018.

### Create an account

* The heading can change to "Create a test account"
* There can also be an alert box under _go back to login_ and above _First name_ that says: "Any test account created during the beta period will be removed from the system when the filing period opens on January 1st, 2018."

### Institutions page

In the alert box add a sentence at the end: "All test data uploaded during the beta period will be removed from the system when the filing period opens on January 1st, 2018."

### Upload page

Above the drag-and-drop box, add an alert box: "All test data uploaded during the beta period will be removed from the system when the filing period opens on January 1st, 2018."

### Signature

* The text under "Signature" can say "To complete your test submission, select the checkbox below. Next, select the "Submit HMDA test data" button to practice submitting data. When the filing period opens, selecting the checkbox will certify the accuracy and completeness of the data submitted. 
* Checkbox text can say "I understand this data being submitted is solely for testing purposes and will be removed from the system when the filing period begins on January 1st, 2018."
* Change button text to "Submit HMDA test data"
* In the green confirmation box, change the heading to: __HMDA test filing accepted__
* Chance the first line in the green box to "Congratulations, you have successfully completed your HMDA test filing!"
* If a confirmation email won't be sent, that line should be removed from the green confirmation box.
