### ISSUE TITLE
Clean up console.log

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#815]
Can we remove all the `if(process.env.NODE_ENV !== 'production')`?

- [this](https://github.com/cfpb/hmda-platform-ui/blob/5395356ef20b382a58ee5ef156b780f3f2c1e998/src/js/index.js#L43)
- [this](https://github.com/cfpb/hmda-platform-ui/blob/5395356ef20b382a58ee5ef156b780f3f2c1e998/src/js/index.js#L62)
- [this](https://github.com/cfpb/hmda-platform-ui/blob/5395356ef20b382a58ee5ef156b780f3f2c1e998/src/js/api/fetch.js#L47)
- [this](https://github.com/cfpb/hmda-platform-ui/blob/5395356ef20b382a58ee5ef156b780f3f2c1e998/src/js/utils/redirect.js#L15)
- [this](https://github.com/cfpb/hmda-platform-ui/blob/5395356ef20b382a58ee5ef156b780f3f2c1e998/src/js/utils/redirect.js#L23)

**Comment by wpears** [comment]
We wants these logs in dev but not prod. An alternate construction would be to create a Log module and only log through that (so in each of these places it would just be
```
import log from '../utils/Log.js'
log(theData)

//in Log.js
export default function(data) {
  if(process.env.NODE_ENV !== 'production') console.log(data)
}
```
