### ISSUE TITLE
Password requirements on "forgot password" page

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#818]
When someone has forgotten their password, they should have the same list of requirements as when they created their initial password. We should add that in here.

### Current content
![screen shot 2017-10-05 at 2 43 48 pm](https://user-images.githubusercontent.com/10562544/31246591-d7d6d2a6-a9db-11e7-9e9c-1a0dbb123ea9.png)

### Requirements list
![screen shot 2017-10-05 at 2 43 58 pm](https://user-images.githubusercontent.com/10562544/31246592-d7db3440-a9db-11e7-9042-97bf8f74b0c6.png)

**Comment by wpears** [comment]
Moved to https://github.com/cfpb/hmda-platform-auth/issues/173
