### ISSUE TITLE
Notify user in platform about time remaining to click email link

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#820]
The alert box says for forgot password says that an email has been sent with further instructions, but can also notify the user about the time limit. 

"You should receive an email shortly with further instructions. You have 60 minutes to confirm your account.
For help with account related issues..."

Interested to know what you think @keileyo .

Here's what it looks like currently:
![screen shot 2017-10-05 at 2 47 01 pm](https://user-images.githubusercontent.com/10562544/31246915-f9843c9e-a9dc-11e7-9ce6-5bef945db8cf.png)

**Comment by wpears** [comment]
Moved to https://github.com/cfpb/hmda-platform-auth/issues/174
