### ISSUE TITLE
Signup link in logged out home page

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#821]
Users had some confusion about where they would go to sign up. They eventually selected the Begin filing or Login button, but they didn't feel either described what they wanted to do. I think we can limit hesitation/friction in the account creation process one of two ways:

* We could include a text link next to the login button that says: "__Create an account__" that goes directly to the account creation page.

* Alternatively, we could add a link in the disclaimer text below the button where it says "register online", but the text is pretty tiny at the moment. If we go with this option, I think the disclaimer text would need to be larger.

![screen shot 2017-10-05 at 9 00 25 am](https://user-images.githubusercontent.com/10562544/31249796-a7c0902e-a9e6-11e7-8391-06223e8c8a49.png)

**Comment by keileyo** [comment]
I would vote for the "Create an account" link next to the login button.
