### ISSUE TITLE
Add latest edit report to History expandable

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#822]
Several filers expected to find the most recent edit report in the "History of this filing" expandable. Can we add it there?

**Comment by awolfe76** [comment]
😄  we had that at one point but it didn't make sense when the title "view previous filings". Now that the title has changed this makes sense. 👍

**Comment by keileyo** [comment]
agreed! everyone thought it should be in there, and I think i even admitted to a few people that we had it that way at one point, and clearly got it wrong by changing it!
