### ISSUE TITLE
Add an icon to drag-and-drop box

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#823]
Before a file has been uploaded, we can speed up visual recognition of the upload box by including an icon. I think this could also increase the likelihood of filers understanding they can click inside the box.

![screen shot 2017-10-05 at 5 46 06 pm](https://user-images.githubusercontent.com/10562544/31254060-2fab56e6-a9f5-11e7-91d5-40ae1c76018d.png)
![screen shot 2017-10-05 at 5 46 21 pm](https://user-images.githubusercontent.com/10562544/31254061-2fc0547e-a9f5-11e7-9909-69c7050ff78d.png)

**Comment by awolfe76** [comment]
@designlanguage - could you upload the image here?

**Comment by awolfe76** [comment]
![uploadicon](https://user-images.githubusercontent.com/2932572/31294162-dc8e8bbe-aaa7-11e7-9801-6619cfb257a7.png)
