### ISSUE TITLE
Duplicate alert banner functionality at the bottom of steps 2, 3, 4

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#829]
Since the alerts aren't persistent (to preserve vertical space), the user won't see the call to action after they've scrolled. We should have those same actions at the bottom of each edits page, especially if there are a lot of edits to review.

### S/V
The strongest case for this is the Syntactical/Validity page. If there are edits here, there is no action that can be taken once a filer has scrolled to the bottom of the page. When S/V edits exist, I propose including modified banner content at the bottom. When they don't exist, it would not be present.

| Current | Proposed |
| --- | --- |
| ![screen shot 2017-10-10 at 11 36 50 am](https://user-images.githubusercontent.com/10562544/31395743-7b480cb2-adaf-11e7-83f3-da0565656992.png) | ![screen shot 2017-10-10 at 11 35 17 am](https://user-images.githubusercontent.com/10562544/31395742-7b320ade-adaf-11e7-9985-700a6ef04d3e.png) |

The content could say something like: "Please review the syntactical and/or validity edits above or __Download the edit report__. Then update your file and select the “Upload a new file” button."

### Q and MQ

For quality and macro, this might be a little different. We already have the verify action at the bottom, but having the option to download the edit report or upload a new file can be there too.

I considered including those option under the "Verify quality edits" heading, but it didn't feel like it belonged there. I'm proposing we include it after the last edit and before the verify heading.

| Pre-verifying | Post-verifying |
| --- | --- |
| ![screen shot 2017-10-10 at 12 13 04 pm](https://user-images.githubusercontent.com/10562544/31397706-befb8c4a-adb4-11e7-8598-9fedbc7aa0f1.png) | ![screen shot 2017-10-10 at 12 13 24 pm](https://user-images.githubusercontent.com/10562544/31397707-bf0ace76-adb4-11e7-8e99-209159202f7a.png) |

The content could say: "__Download the edit report__ of the quality edits listed above. 
If the data needs to be corrected, update your file and __Upload a new file__." After the verify checkbox is selected, the second sentence can be removed.

Thoughts @keileyo ?

**Comment by keileyo** [comment]
I do think that it would be nice to have the edit reports below. I would slightly tweak the language. How about:
"Please review the edits above or **download the edit report**. If the data need to be corrected, update your file and **upload a new file**.
