### ISSUE TITLE
Update browserblocker?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#838]
Do we need to update the [browser check](https://github.com/cfpb/hmda-platform-ui/blob/8711ad68858b86a52ccb14c6311bc238a41a48a0/src/js/containers/App.jsx#L68) to be in line with what we've done [here](https://github.com/cfpb/hmda-platform-ui/blob/10b238d155adf37127754de7760507d4ef45c73a/.babelrc#L7)?

**Comment by awolfe76** [comment]
List for the package we're using can be found [here](https://github.com/DamonOehlman/detect-browser/blob/master/index.js).

**Comment by wpears** [comment]
While we're only targeting what's listed in `.browserslistrc` specifically, the inclusion of ie11 as a targeted browser will cover Chrome/FF/Safari/Edge as far as polyfills go, etc. Thus, I think the simple approach we have for testing ie<11 works here (people truly unsupported and off auto-update cycles).
