### ISSUE TITLE
Rework institution/edit report data structure

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#89]
the /submit screen needs to know the status of the submission so it knows which components to show.

This will require careful thought on URL structure and the data captured within each "edit report" (maybe actually should hold an array of submissions each of which only has a single edit report)

**Comment by awolfe76** [comment]
#36 has the start to some thoughts on this ... and then add in the idea of each edit report.

It also seems like [`institutions.js`](https://github.com/cfpb/hmda-platform-ui/blob/master/src/js/data/institutions.js) has some of this. 

Or are you talking about something else?

I also think it would be useful to bring back the first `n` edits for each edit type if they exist. So if the status is 8 (from [here](https://github.com/cfpb/hmda-platform/issues/264#issuecomment-203686220)) we would know how to render the progress, the nav, and be able to show the first few edits as well. We could then easily render the first `n` results for each without requiring another API call. The API call would only be needed when we do the "show 5 more".

Would be nice to get as much as we can with 1 API call.

**Comment by wpears** [comment]
Yeah I'm expanding `institutions.js` and updating things to work off the 11 proposed statuses in https://github.com/cfpb/hmda-platform/issues/264#issuecomment-203686220 with special regard to how the router functions and how different runs through the app will be separated in the data (an array of `submissions` with more fields than `institutions.js` currently has).

**Comment by wpears** [comment]
Closed by #99
