### ISSUE TITLE
Add institution name or id to file downloads

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#899]
Both the edit report and IRS `.csv` downloads are named using the submission number.

For example, `3-full-edit-report.csv` and `3-irs-report.csv`.

We should add in either the institution name or id to make the file names more clear and to prevent the possibility of overwriting files when a filer is filing for multiple institutions.

**Comment by wpears** [comment]
It would never overwrite, just create `3-irs-report (1).csv` etc., but I agree it's nice for clarity.
