### ISSUE TITLE
List edits in numerical order

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#902]
The order that the edits are listed in each step should proceed from the lowest number to highest.

Right now the platform lists edits in the order they're triggered, but that doesn't help the user, especially if there are multiple instances of an edit. 

So currently the platform may return an order of:
Q044
Q014
Q032

But ideally, it can be presented to the user in numerical order, like this:
Q014
Q032
Q044

**Comment by colleenms** [comment]
Great suggestion, we received the same feedback from users via the HMDA Feedback inbox. The edits in the FIG and the downloadable Edit Report are organized in numerical order, which can make resolving edits particularly challenging for users.

**Comment by schbetsy** [comment]
This sounds like it might be a back-end ticket. Agree, @awolfe76 / @wpears ?  Want me to look into it?

**Comment by wpears** [comment]
Sure. Seems like we'd want the API returning numerical order for the same reason.
