### ISSUE TITLE
Change filing status content on home page: created

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#904]
"Created" is misleading to a user that hasn't uploaded a file yet.
Also, the text about resubmission should only appear when a resubmission is a possibility, it's confusing when it appears before a file has even been uploaded.

There is also less color given to the status because that will be taken up by the steps being shown in the institution box.

| Current text | Change to |
| --- | --- |
| ![screen shot 2017-11-21 at 12 05 20 pm](https://user-images.githubusercontent.com/10562544/33086195-eca5ba78-ceb4-11e7-833b-395f317dadf1.png) | ![screen shot 2017-11-21 at 11 55 39 am](https://user-images.githubusercontent.com/10562544/33085883-091ad9d2-ceb4-11e7-8ee2-435f1aa3116f.png) |

The proposed revision:

### No data has been uploaded yet. 
The filing period is open available to accept HMDA data. Make sure your data is in a pipe-delimited text file.
__Upload your file__

**Comment by colleenms** [comment]
Agree that a status of "Created" and the accompanying text is misleading. Another alternative is to have a filing status of "Not Started" instead of "No data has been uploaded yet", with the remaining text you proposed below.

**Comment by designlanguage** [comment]
@colleenms - Since we're leaving off "filing status:", we might need a little more context than "Not started". It could say something like "Your filing has not started."

Sidenote: the reason I'm recommending leaving off "filing status:" is because showing the step icons in the box is the status.
