### ISSUE TITLE
Change filing status content on home page: Parsed with errors

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#905]
The filing status text has proven confusing to users. They aren't sure what "parsed" means. Furthermore the text about resubmission should only appear when a resubmission is a possibility.

There is also less color given to the status because that will be taken up by the steps being shown in the institution box.

| Current text | Change to |
| --- | --- |
| ![screen shot 2017-11-21 at 12 05 52 pm](https://user-images.githubusercontent.com/10562544/33086196-ecb5bfa4-ceb4-11e7-9698-719f40a7817e.png) | ![screen shot 2017-11-21 at 12 00 02 pm](https://user-images.githubusercontent.com/10562544/33085884-0927027a-ceb4-11e7-893e-920f423ec690.png) |

The proposed revision: (note - if the home page knows the file name, we can call it out specifically: __Bank0-HMDA2.text has formatting errors.__ )

### Your data has formatting errors.
Review these errors and update your file. Then, upload the corrected file.
__Review formatting errors__

**Comment by colleenms** [comment]
Another alternative is to have a filing status of "uploaded with errors" followed by your proposed text to make it more clear that only the upload step was completed.

**Comment by designlanguage** [comment]
@colleenms - I think it's important to include "formatting" in the heading, because some users thought "errors" meant "edits". Also, the upload step wouldn't really be complete at this point, since the file has formatting errors.
