### ISSUE TITLE
Move formatting errors above upload box

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#913]
We saw several users miss the listing of formatting errors because they didn't scroll. This is what they're seeing, and there isn't much indication that they need to look lower on the page.

![screen shot 2017-11-22 at 12 03 18 pm](https://user-images.githubusercontent.com/10562544/33140226-5cb73378-cf7d-11e7-8951-0e0c21168042.png)

Even with the test data message going away when filing season opens, the list still may not make it above the fold. At this point in the process, it's important that a user understands what's wrong with their file, so I recommend showing the formatting errors above the upload box.

Uploading is still actionable above the fold with the "upload a new file" button in the error message, so I don't think we're losing anything significant by moving the box.

**Comment by colleenms** [comment]
Agree, we've received multiple HMDA Feedback inquiries from institutions that didn't know what errors were found in their file because they didn't scroll down the page.

**Comment by designlanguage** [comment]
We decided in discussion that the page would automatically scroll down to the errors if there are any.
