### ISSUE TITLE
Move alert warning for parse errors lower?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#937]
With #936 merged, the alert at the top of the page for parsing errors is offscreen almost immediately. Would it be better to move it lower, to the scroll point?

#### Suggestion?

![no-warning](https://user-images.githubusercontent.com/2932572/33909140-9118e5ea-df58-11e7-8827-9f6a165dff99.png)

**Comment by designlanguage** [comment]
@awolfe76 - I like that solution.
