### ISSUE TITLE
NavButton action blocked by footer on very small screens

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#942]

**Comment by awolfe76** [comment]
Yeah, there are a few, not very good, things that happen on small screens.

But we decided at the beginning the mobile wouldn't be a focus. Also, analytics show the less than 3% of our users are coming in on mobile and tablet and __less than 0.02%__ are are coming in with a browser width of 800px or less.

I think we're ok here, for now, we haven't heard anyone with complaints. But, for 2018 I want us to take a different approach and build for mobile first. While uploads won't happen from these devices, at the very least someone should be able to easily view the status and edits, verify edits, and sign.
