### ISSUE TITLE
Large LAR files generating error message

### ISSUE THREAD

**Issue by colleenms** [cfpb/hmda-platform-ui#948]
Users uploading large LAR files (>100k) are reporting receiving the below error message and needing to refresh the page multiple times during the submission process. They are able to complete a submission.

![image](https://user-images.githubusercontent.com/32906749/34018052-4e6436ba-e0f6-11e7-8515-efeb9c8e7e48.png)

**Comment by wpears** [comment]
This error message is when the backend reports an internal server error (error code 500). Worth noting this on the backend repo.

**Comment by awolfe76** [comment]
Closing, see https://github.com/cfpb/hmda-platform/issues/1410.
