### ISSUE TITLE
Change heading on logged out page 

### ISSUE THREAD

**Issue by designlanguage** [cfpb/hmda-platform-ui#949]
Post beta, the heading on the logged out page will say __"Get started with the HMDA Platform"__. Pre-beta the heading was __"Get started filing your HMDA data"__.

I prefer the pre-beta message because it's more actionable/relatable, but want to make sure this wasn't changed for a specific reason. 

Does that sound good, @keileyo?

**Comment by keileyo** [comment]
sounds good to me. i like "Get started filing your HMDA data."
