### ISSUE TITLE
Pull edit messages (official and human readable) from external source

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-platform-ui#96]
The actual text could be embedded in the table, or the edit ID could be a link to a HMDA Help site which has a table of Edits and explanations.

**Comment by debseidner** [comment]
This could be helpful for FIs to respond to Macro Edits during edit validation. The filers could use the suggested drop down list (maybe we could publish that somewhere) for each edit and upload a file with the edit number and reason and then load that to the UI during submission. There is a different list for each edit of dropdown possibilities so we would need to check that the FI is picking a valid selection for that macro edit.

**Comment by debseidner** [comment]
We could also try to let FIs verify the quality edits through an external file. They could have to download our edit report, add in a verification code onto each row and upload it back to their submission in our tool so they don't have to go through each edit individually or on their side everytime they reload their file and check it, they can keep track of what they have verified already. This would have to be by loan and by edit number.

**Comment by awolfe76** [comment]
See #150

**Comment by awolfe76** [comment]
Depends on https://github.com/cfpb/hmda-platform/issues/717

**Comment by awolfe76** [comment]
Closing. On the back-end https://github.com/cfpb/hmda-platform/issues/717 handles this.
And #300 on the front-end.
