### ISSUE TITLE
Wait to get edits until needed

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#971]
We can do something to help with https://github.com/cfpb/hmda-platform/issues/1410.

When progress finishes on an upload with call the `/edits` endpoint which returns us the list of edits found, along with their descriptions. This part is fine and gives us enough information about the edits to handle the navigation.

But, we also immediately call the `edits/<edit>` for each edit returned in the list above. This could be a lot of edits. We should wait to call for edits until the filer goes to that page. So call for syntactical and validity edits when they navigate to that page. Same for quality and macro edits ... especially in this case. We don't need quality and macro until all syntactical and validity have passed anyway.

**Comment by wpears** [comment]
To clarify, this will only hit the `edits/<edit>` endpoint for each *type* of edit, so maximum 42 and on average probably ~10ish. There may be a lot of rows that fail each edit, but they are paginated so we're only getting data about 20 rows per edit for ~10 edits which only ends up being 20kb or so. So were aren't saturating the network or anything.

It's more likely that the pagination implementation is pulling all the data into memory or something which is crashing an actor. That said, from initial testing it seems like the `/edits` endpoint itself is failing, so it seems to me that edits filling up memory isn't the current problem (though it may be a problem).

That said, it's certainly true that we don't need to **ever** request quality and macro edits if syn/val exist, so we shouldn't. This will reduce the number of requests after validation completes approximately by half.
