### ISSUE TITLE
While still processing, progress says 100%

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-platform-ui#972]
When a large file is uploaded, and you leave the app and come back, the progress bar says 100% but the content still says "validating edits ...".

Can we make this either
- start over, or
- start at some other percentage?

---

#### Screenshot

![large-file](https://user-images.githubusercontent.com/2932572/34991902-4868f6ee-fa99-11e7-89b2-29f613aea690.png)

**Comment by schbetsy** [comment]
(Disregard if this adds too much complexity, but) Maybe if the status is "uploading" it shouldn't get past 25%, then "parsing" could be up to 50%, then validating could be the rest.

I noticed when uploading large files that sometimes the upload takes so long that the progress bar gets up to 60% or so just on the upload stage.
